/**
 * Single source of truth for the audit host's <head> metadata copy —
 * imported by BOTH the client-side effect (LandingPage.jsx's
 * useLandingMeta, LiteWidget.jsx's report/status head) and the
 * build-time static-head Vite plugin (vite.config.js), so the
 * prerendered HTML and the client's runtime <head> mutations can never
 * disagree (S1/S2). Deliberately plain JS — no import.meta.env, no
 * React — so vite.config.js (a Node/ESM context, not a Vite-transformed
 * app module) can import it directly. That's also why the OG image is
 * exported as a root-relative PATH rather than an absolute URL: each
 * consumer composes the absolute URL from the base it can actually see
 * (the plugin from loadEnv()'s VITE_PUBLIC_AUDIT_BASE_URL, the client
 * from publicUrls.js's env-aware PUBLIC_AUDIT_BASE_URL — which would
 * throw here, since import.meta.env doesn't exist in vite.config.js's
 * own plain-Node execution). That split is also what lets the audit
 * surface move under a base path (parleo.io/audit) without this file
 * having to know anything about where it is served from.
 */
export const LANDING_META_TITLE = 'Parleo Audit — how AI shopping agents see your store'
export const LANDING_META_DESCRIPTION =
  'A free audit of what agentic shoppers actually see when they read your store: pricing, membership terms, and structured data.'

// The neutral title for /r/{token} and /s/{id} documents (S3) — never
// the landing title, and never brand-specific: a shared report link
// must not unfurl like marketing content for the audit tool itself.
export const REPORT_META_TITLE = 'Parleo Audit'

// S4/Part 3: the landing's share card — a static 1200x630 PNG
// (public/og/audit-landing.png, generated by
// scripts/generate-og-image.mjs from scripts/og-image-design.html —
// see that file's own comment for the rationale and the numbers'
// provenance). Root-relative on purpose (see the module comment): both
// consumers prefix it with their own audit base URL, so the emitted
// tag is https://audit.parleo.io/og/... today and
// https://parleo.io/audit/og/... under a VITE_PUBLIC_AUDIT_BASE_URL
// build, from one path literal. Every consumer must still treat a null
// value here as "omit the tag entirely" if this is ever reset — never
// fabricate a path that would just 404 on every unfurl.
export const OG_IMAGE_PATH = '/og/audit-landing.png'
export const OG_IMAGE_WIDTH = 1200
export const OG_IMAGE_HEIGHT = 630
export const OG_IMAGE_ALT = 'Parleo free Agentic Value Audit sample report card'
