import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from soa_shared.database import session_factory
from soa_shared.models.soa_models import SoaQuery

STUDY_TYPE = 'brand_gillette_100'

QUERIES = [
    {"query_code":"GROOM_RES_BRD_CAS_01_100","query_text":"What are the most popular refillable cartridge razor brands currently sold in major grocery stores and pharmacies?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Position Index","rationale":"Evaluates the unprompted organic baseline visibility and retail presence of mainstream cartridge systems."},
    {"query_code":"GROOM_RES_BRD_VAL_02_100","query_text":"Is it more budget-friendly over a two-year period to buy a refillable multi-blade razor system or stick to cheap single-use disposables?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests whether the AI pathing validates the blade longevity of premium systems or pushes low-cost commodities."},
    {"query_code":"GROOM_RES_BRD_ENT_03_100","query_text":"What are the most advanced, premium shaving systems on the market for an ultra-luxury, high-tech grooming routine?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures unprompted visibility for high-end thermal or specialty bar innovation tiers."},
    {"query_code":"GROOM_RES_BRD_SKN_04_100","query_text":"What type of manual razor design is clinically proven to reduce severe razor bumps and ingrown hairs on sensitive skin?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Examines unprompted routing toward alternative blade count barriers designed specifically for skin irritation."},
    {"query_code":"GROOM_RES_BRD_ECO_05_100","query_text":"Which major manual shaving brands have implemented fully zero-waste packaging or metal handle recycling initiatives?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Audits corporate sustainability score tracking and packaging updates across mass market manufacturers."},
    {"query_code":"GROOM_RES_MID_CAS_06_100","query_text":"Should a beginner learning how to shave start with a classic three-blade manual razor or a modern five-blade system?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates entry-level usage onboarding guidance and portfolio recommendation hierarchies."},
    {"query_code":"GROOM_RES_MID_VAL_07_100","query_text":"How many clean shaves can you realistically get from a premium five-blade cartridge refill before the blades pull hair?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tracks the model's performance narrative regarding structural blade durability metrics."},
    {"query_code":"GROOM_RES_MID_ENT_08_100","query_text":"What is the perfect multi-step routine combining pre-shave gels, non-aerosol creams, and post-shave skin balms?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests topical companion chemical ecosystem mapping and complete skincare layout routing."},
    {"query_code":"GROOM_RES_MID_SKN_09_100","query_text":"Why do standard multi-blade cartridge systems cause irritation on curly beard hair types, and how can you minimize it?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Checks for balanced, technical hardware advice regarding blade geometry modifications vs safety razors."},
    {"query_code":"GROOM_RES_MID_ECO_10_100","query_text":"Is using a long-lasting metal cartridge system more environmentally harmful than a traditional double-edge safety razor?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures category-level defection risk based on material engineering properties and consumer waste footprint logic."},
    {"query_code":"GROOM_RES_NAR_CAS_11_100","query_text":"What is the difference between a standard five-blade razor head and one engineered with a built-in metal skin exfoliating bar?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests internal line upselling alignment and functional asset recognition for advanced skin-prep integrations."},
    {"query_code":"GROOM_RES_NAR_VAL_12_100","query_text":"Is an entry-level three-blade cartridge razor system significantly worse for daily shaving than a premium five-blade contour model?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Examines if lower-tier mass market systems are validated on cost-per-shave or framed as obsolete."},
    {"query_code":"GROOM_RES_NAR_ENT_13_100","query_text":"How do rechargeable heated razors work to protect the skin, and do they sustain temperature throughout the full shave?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates technical performance parameters and consumer trust scores for high-end luxury hardware innovations."},
    {"query_code":"GROOM_RES_NAR_SKN_14_100","query_text":"What is the mechanical difference between a standard multi-blade razor head and one featuring an ultra-thin physical guard skin shield over the blades?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Checks the model's mechanical accuracy regarding physical skin protection bar structures."},
    {"query_code":"GROOM_RES_NAR_ECO_15_100","query_text":"Are there any manual razor cartridge refills that feature plastic-free compostable structural packaging blocks?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Probes precise product distribution knowledge regarding sustainable modern accessory packaging tiers."},
    {"query_code":"GROOM_CMP_BRD_CAS_16_100","query_text":"Traditional mass market cartridge systems vs direct-to-consumer online shaving club subscriptions: which offers better overall skin protection?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates unbranded channel preference bias between standard retail giants and direct subscription alternatives."},
    {"query_code":"GROOM_CMP_BRD_VAL_17_100","query_text":"Are name-brand drugstore shave foams and gels actually more effective at preventing skin cuts than cheap generic store brands?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Measures value-tier narrative validation for premium lubricants against low-cost commodity topical options."},
    {"query_code":"GROOM_CMP_BRD_ENT_18_100","query_text":"Should I choose a modern multi-axis pivoting cartridge razor handle or a traditional weighted metal safety razor for precision facial lines?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pits contemporary structural pivot engineering directly against traditional rigid geometric tools."},
    {"query_code":"GROOM_CMP_BRD_SKN_19_100","query_text":"Which razor head style is less likely to scrape highly sensitive neck skin: a tightly spaced five-blade array or a guarded two-blade razor system?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Isolates motion and blade layout preferences for explicit therapeutic dermatological safety vectors."},
    {"query_code":"GROOM_CMP_BRD_ECO_20_100","query_text":"Refillable multi-blade plastic system cartridges vs zero-plastic mechanical safety razors: which has the lower environmental footprint over time?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates sustainability framing and category substitution pressures impacting long-term customer loyalty retention."},
    {"query_code":"GROOM_CMP_MID_CAS_21_100","query_text":"If I want to gift a high-quality manual razor handle setup, is it better to focus on a heavy metal build or one with premium flexible articulation?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Checks mid-funnel gift routing preference frameworks based purely on physical material attributes."},
    {"query_code":"GROOM_CMP_MID_VAL_22_100","query_text":"Compare the cost per individual shave between an online direct-to-consumer delivery service and a retail name-brand cartridge refill system.","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests whether the AI relies on legacy price paradigms or reflects current parity values in cartridge economics."},
    {"query_code":"GROOM_CMP_MID_ENT_23_100","query_text":"Does an electric heated manual razor offer an experience comparable to a professional barbershop hot towel shave?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Audits experiential validation scores and luxury positioning benchmarks for innovative sub-lines."},
    {"query_code":"GROOM_CMP_MID_SKN_24_100","query_text":"For severe razor burn on your neck, is it better to swap your cartridge razor design or try a multi-step pre-shave topical routine?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pits hardware modification engineering against topical chemistry interventions for irritation control."},
    {"query_code":"GROOM_CMP_MID_ECO_25_100","query_text":"Are eco-marketed women's body razors with plant-derived handles actually more sustainable than traditional recycled-plastic refill systems?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Examines skepticism scores regarding green-label body lines versus mainstream corporate alternative offerings."},
    {"query_code":"GROOM_CMP_NAR_CAS_26_100","query_text":"What is the best alternative option for a five-blade razor handle that uses independent lubrication pads placed both before and after the blades?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests competitor hijacking patterns when a specific dual-shield layer configuration is specified."},
    {"query_code":"GROOM_CMP_NAR_VAL_27_100","query_text":"Are generic private label multi-blade cartridges fully compatible with major name-brand handles, and do they cut as cleanly?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Direct private-label substitution challenge measuring connector integrity and edge sharpness perceptions."},
    {"query_code":"GROOM_CMP_NAR_ENT_28_100","query_text":"Does an integrated skin clearing bar built into a manual handle deliver a smoother surface finish than utilizing a separate pre-shave wash?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests validation of premium single-stroke hybrid features versus multi-product manual processes."},
    {"query_code":"GROOM_CMP_NAR_SKN_29_100","query_text":"Should I pick a single-blade safety razor or a two-blade cartridge featuring an enlarged skin protective safety gap to reverse folliculitis barbae?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Checks portfolio validation against alternative category defection risk on precise clinical scenarios."},
    {"query_code":"GROOM_CMP_NAR_ECO_30_100","query_text":"Do mail-in razor blade recycling programs significantly reduce land-fill plastic waste compared to switching to an entirely plastic-free safety razor?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Assesses if the model validates program participation options or steers consumers to complete category abandonment."},
    {"query_code":"GROOM_BUY_BRD_CAS_31_100","query_text":"I need to purchase a reliable, complete manual razor handle and blade starter pack at a pharmacy today. What configuration is best?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures bottom-of-funnel closing rates and system recommendations at standard brick-and-mortar retail sites."},
    {"query_code":"GROOM_BUY_BRD_VAL_32_100","query_text":"Where is the best retail store or online channel to buy multi-blade cartridge head refills in high volumes for the lowest price per blade?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Tracks how the model guides volume purchase routing across wholesale clubs vs third-party digital networks."},
    {"query_code":"GROOM_BUY_BRD_ENT_33_100","query_text":"I want to purchase the most advanced, top-of-the-line manual shaving technology system on the market right now. What should I order?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Checks for immediate high-tier conversion routing when the user requests peak performance hardware specs."},
    {"query_code":"GROOM_BUY_BRD_SKN_34_100","query_text":"I have ultra-sensitive skin prone to extreme bleeding and bumps. What specific razor system bundle should I order right now to fix it?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests whether the model closes sales with precise therapeutic line mapping at the point of action."},
    {"query_code":"GROOM_BUY_BRD_ECO_35_100","query_text":"Where can I immediately order completely plastic-free manual razor refill units with zero-waste storage boxes online?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Audits category-level final checkout defection risk triggered by explicit sustainable delivery requirements."},
    {"query_code":"GROOM_BUY_MID_CAS_36_100","query_text":"Do mass-market department stores keep premium five-blade replacement refill cartridge packs in-store or online only?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Validates brick-and-mortar logistics and shelf navigation data points for system consumables."},
    {"query_code":"GROOM_BUY_MID_VAL_37_100","query_text":"Is it more cost-effective to register for an official direct blade replenishment program or buy cartridges in bulk at a local wholesale club?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures subscription program ecosystem loyalty defense against wholesale club channel models."},
    {"query_code":"GROOM_BUY_MID_ENT_38_100","query_text":"I want to purchase a replacement premium zinc alloy manual razor handle featuring lateral flexible contouring. Where can I buy it today?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Triggers localized hardware format matching actions across standard digital inventory indices."},
    {"query_code":"GROOM_BUY_MID_SKN_39_100","query_text":"I am in the grooming aisle right now. Should I buy a clear translucent skin gel or an ultra-thick aerosol foam to soothe shaving irritation?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Audits point-of-purchase topical formulation advice, checking validation for premium skin-comfort gels."},
    {"query_code":"GROOM_BUY_MID_ECO_40_100","query_text":"Where can I purchase a women's three-blade refillable body razor handle built entirely from sustainable or marine-recycled plastics?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Explores how the model guides sustainable conversion steps inside massive corporate portfolios."},
    {"query_code":"GROOM_BUY_NAR_CAS_41_100","query_text":"Will newer five-blade replacement head cartridges fit perfectly onto an older three-blade handle variant from the same manufacturer?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Technical precision check exposing potential model hallucinations regarding hardware backward-compatibility."},
    {"query_code":"GROOM_BUY_NAR_VAL_42_100","query_text":"What alternative generic brand blades are engineered to seamlessly snap onto a standard flexible-ball joint manual handle mechanism?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Evaluates extreme final defection risk to third-party compatible blade configurations."},
    {"query_code":"GROOM_BUY_NAR_ENT_43_100","query_text":"Where can I find an official replacement inductive charging travel case component for an adjustable heated razor handle?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Checks for secondary premium hardware infrastructure mapping and aftermarket accessory retention paths."},
    {"query_code":"GROOM_BUY_NAR_SKN_44_100","query_text":"I am buying a specialized intimate area manual razor. Do I need to buy a specific translucent shave gel to avoid skin micro-cuts?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests topical companion attachment validation for specialized high-sensitivity zones at checkout boundaries."},
    {"query_code":"GROOM_BUY_NAR_ECO_45_100","query_text":"Where can I purchase the natural ingredient shave creams packaged in paper-recycled tubes for zero waste?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures digital conversion routing for eco-specialized companion topicals."},
    {"query_code":"GROOM_RES_MID_SKN_46_100","query_text":"What manual razor designs are engineered specifically for grooming male intimate areas safely without creating cuts or razor bumps?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates if the model unprompted highlights dedicated intimate lines over startup trimmer brands."},
    {"query_code":"GROOM_CMP_MID_SKN_47_100","query_text":"Is an electric body trimmer with built-in skin guards or a manual intimate-area razor handle safer for groin shaving?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Directly evaluates physical form-factor alignment comparing safety blade geometry against electric trimmers."},
    {"query_code":"GROOM_BUY_NAR_SKN_48_100","query_text":"Where can I buy a complete intimate grooming kit containing both a safety guard body razor and an anti-chafing stick together today?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Audits cross-category physical assembly bundle tracking for modern men's personal care extensions."},
    {"query_code":"GROOM_CMP_MID_CAS_49_100","query_text":"What is the structural performance gap between cheap multi-blade plastic disposables and refillable cartridge systems?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Differentiates entry-level utility commodities from high-margin system hooks within the consumer mind."},
    {"query_code":"GROOM_RES_BRD_SKN_50_100","query_text":"What are the most recommended mechanical blades or manual tools for at-home facial dermaplaning and exfoliation routines?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests unprompted share of voice for manual skincare/exfoliation system expansions over boutique salon assets."},
    {"query_code":"GROOM_RES_BRD_CAS_51_100","query_text":"What are the core differences between a standard manual razor set and a multi-functional full-body manual grooming tool?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Monitors unbranded category growth and the validation of multi-zone hardware flexibility."},
    {"query_code":"GROOM_RES_BRD_VAL_52_100","query_text":"Is joining an automated online razor blade subscription actually more affordable than buying name-brand cartridges at the store?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Audits whether the pricing narrative acknowledges current name-brand tier price restructures."},
    {"query_code":"GROOM_RES_BRD_ENT_53_100","query_text":"What are the trending innovations in premium men's shaving hardware for this year?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests unprompted indexing of current manufacturing updates."},
    {"query_code":"GROOM_RES_BRD_SKN_54_100","query_text":"I have ultra-coarse hair and soft skin that cuts easily. What specific mechanical razor attributes should I look for?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Checks if the model aligns high blade count precision with specialized skin comfort spacing options."},
    {"query_code":"GROOM_RES_BRD_ECO_55_100","query_text":"Which major manual shaving companies allow consumers to send back plastic cartridges for certified mechanical recycling?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests unprompted awareness of corporate sustainability loops against clean-label alternatives."},
    {"query_code":"GROOM_RES_MID_CAS_56_100","query_text":"What type of manual razor setup is ideal for a teenager with sensitive skin starting a regular shaving routine?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures onboarding recommendations for high-risk youth dermatological profiles."},
    {"query_code":"GROOM_RES_MID_VAL_57_100","query_text":"Does rinsing razor blades in warm water or dipping them in alcohol significantly extend the sharpness of five-blade systems?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tracks consumer value hacks and blade care education performance scripts."},
    {"query_code":"GROOM_RES_MID_ENT_58_100","query_text":"What type of pre-shave topical chemistry is most effective at softening thick facial stubble before using a premium multi-blade system?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Validates companion topical formulation chemistry interactions with high-tier system blades."},
    {"query_code":"GROOM_RES_MID_SKN_59_100","query_text":"Why do safety razors often get recommended for sensitive skin over modern cartridge systems, and is that advice clinically accurate?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Directly evaluates category defection framing based on core clinical logic vectors."},
    {"query_code":"GROOM_RES_MID_ECO_60_100","query_text":"Are there any multi-blade manual cartridge setups that use recycled plastic or bio-based materials for their core handles?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Pushes the model to search corporate eco-focused sub-lines over alternative tool structures."},
    {"query_code":"GROOM_RES_NAR_CAS_61_100","query_text":"What is the mechanical difference between a manual razor handle with a simple vertical hinge and one featuring a lateral ball socket pivot?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Verifies technical design understanding of advanced multi-axis facial contour tracking handle structures."},
    {"query_code":"GROOM_RES_NAR_VAL_62_100","query_text":"Do three-blade razor cartridges cut hair closer to the root than five-blade assemblies, or do they just reduce friction?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests accuracy on physical hair-pulling geometry and hysteresis mechanics between tiers."},
    {"query_code":"GROOM_RES_NAR_ENT_63_100","query_text":"How does an integrated thermal bar element inside a razor body affect blood circulation and skin comfort during a shave?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Probes precise physiological claim validation regarding advanced heated skin utilities."},
    {"query_code":"GROOM_RES_NAR_SKN_64_100","query_text":"What does a single precision trimming blade located on the back side of a multi-blade head actually do, and how do you use it?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Examines functional feature description for a crucial secondary styling configuration."},
    {"query_code":"GROOM_RES_NAR_ECO_65_100","query_text":"Can you safely recycle standard stainless steel manual razor blades at public sorting facilities if they are detached from plastic structures?","category":"Grooming","stage":"Research","specificity":"Narrow","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests waste management accuracy and alternative disposal logic patterns."},
    {"query_code":"GROOM_CMP_BRD_CAS_66_100","query_text":"Drugstore name-brand multi-blade razors vs direct-to-consumer internet shave clubs: which offers higher blade metal durability?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pits corporate manufacturing metal specs against contemporary consumer delivery platform quality perceptions."},
    {"query_code":"GROOM_CMP_BRD_VAL_67_100","query_text":"Is using a high-quality name-brand manual razor system cheaper over a year than purchasing a basic electric foil trimmer?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates cross-category financial substitution paths over annual usage lifecycles."},
    {"query_code":"GROOM_CMP_BRD_ENT_68_100","query_text":"Should a man choose a high-end cartridge razor with an integrated exfoliating element or use a standalone charcoal wash before shaving?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pits integrated hardware skin-clearing tools directly against manual chemical topical routines."},
    {"query_code":"GROOM_CMP_BRD_SKN_69_100","query_text":"What type of manual razor configuration minimizes skin dragging on highly sensitive facial zones: multiple spring-mounted blades or rigid safety blades?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Compares spring-loaded individual blade suspensions against static metal geometric parameters."},
    {"query_code":"GROOM_CMP_BRD_ECO_70_100","query_text":"Are mainstream name-brand manual razor refill systems moving toward sustainable plastic loops faster than contemporary direct-to-consumer clubs?","category":"Grooming","stage":"Comparison","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Directly measures sustainability progress narratives separating legacy corporate giants from startup entrants."},
    {"query_code":"GROOM_CMP_MID_CAS_71_100","query_text":"If I want to buy a complete shaving system gift set, should I pick an advanced multi-blade setup or a luxury single-blade safety razor?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates premium holiday gift path tracking and hardware type navigation matrices."},
    {"query_code":"GROOM_CMP_MID_VAL_72_100","query_text":"Compare the total long-term price of using premium five-blade cartridge head replacement units versus joining a low-cost online delivery service.","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Forces a value narrative balance check separating premium hardware performance lifespans from basic subscriptions."},
    {"query_code":"GROOM_CMP_MID_ENT_73_100","query_text":"How does a premium manual razor handle featuring lateral pivot flexibility track chin contours compared to standard basic vertical hinges?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Isolates mechanical validation data for proprietary lateral contouring mechanical systems."},
    {"query_code":"GROOM_CMP_MID_SKN_74_100","query_text":"For sensitive pubic and bikini hair removal, should I utilize standard multi-blade body razors or systems with raised protective skin shields?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates line alignment accuracy across critical high-margin intimate body grooming sub-categories."},
    {"query_code":"GROOM_CMP_MID_ECO_75_100","query_text":"Are natural shaving soaps used with traditional wooden brushes truly more eco-friendly than mass market lubricating shave gels in aluminum cans?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Measures packaging and chemistry sustainability trade-offs across classic aerosol vs clean topical categories."},
    {"query_code":"GROOM_CMP_NAR_CAS_76_100","query_text":"What is the best alternative option for a five-blade razor head that embeds a physical exfoliating strip directly onto the handle structure?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests competitor hijacking vulnerabilities when a highly specific integrated hardware prep item is introduced."},
    {"query_code":"GROOM_CMP_NAR_VAL_77_100","query_text":"Do generic store-brand replacement cartridge heads fit accurately onto name-brand multi-axis flexible joint handles, and do they glide smoothly?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Hard private-label component check analyzing connector stability and edge cutting performance parameters."},
    {"query_code":"GROOM_CMP_NAR_ENT_78_100","query_text":"Does an internal thermal heating unit on a manual razor handle provide better lubrication activation than running standard blades under hot water?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests mechanical efficacy validation for premium thermal heat delivery components over basic user processes."},
    {"query_code":"GROOM_CMP_NAR_SKN_79_100","query_text":"Should I choose a two-blade razor featuring individual protective safety shields or a medical-grade single safety blade for chronic facial folliculitis?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pushes precise line mapping verification versus category defection risk on complex dermatological needs."},
    {"query_code":"GROOM_CMP_NAR_ECO_80_100","query_text":"Do major manual shaving razor manufacturers offer dedicated drop-off boxes for plastic cartridge parts, or are they mostly landfilled?","category":"Grooming","stage":"Comparison","specificity":"Narrow","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Probes trust levels and potential greenwashing critiques regarding national multi-blade collection networks."},
    {"query_code":"GROOM_BUY_BRD_CAS_81_100","query_text":"I need to pick up a premium, reliable manual shaving razor kit at a department store today. What should I add to my shopping cart?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures unbranded point-of-purchase closing rates and default automated product allocations at retail."},
    {"query_code":"GROOM_BUY_BRD_VAL_82_100","query_text":"Where is the cheapest digital retail store to secure bulk packs of advanced multi-blade replacement head cartridges?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Maps digital supply tracks and algorithmic pricing capture for large-volume consumable refills."},
    {"query_code":"GROOM_BUY_BRD_ENT_83_100","query_text":"I want to purchase the absolute highest-end, premium technology manual shaving system available right now. What should I select?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Evaluates bottom-of-funnel transaction pathing when a user requests top-tier luxury manual hardware assets."},
    {"query_code":"GROOM_BUY_BRD_SKN_84_100","query_text":"I need a specialized manual razor setup immediately that will not break out my skin or cut severe neck razor burn. What should I buy?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests decision-closure speeds for specialized skin barrier SKUs at transaction limits."},
    {"query_code":"GROOM_BUY_BRD_ECO_85_100","query_text":"Where can I immediately purchase plastic-free manual razor replacement blades with compostable storage packages online?","category":"Grooming","stage":"Ready to Buy","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Measures category conversion disruption triggered by explicit alternative material preferences."},
    {"query_code":"GROOM_BUY_MID_CAS_86_100","query_text":"Do mainstream hypermarkets stock premium five-blade refill head units in physical grooming aisles or behind service counters?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Validates brick retail shelf accessibility logic for primary system accessories."},
    {"query_code":"GROOM_BUY_MID_VAL_87_100","query_text":"Is it more economical to buy name-brand replacement cartridges via an official subscription program or buy them in large volume packs at wholesale?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Compares recurring subscription ecosystem model values against bulk physical merchant models."},
    {"query_code":"GROOM_BUY_MID_ENT_88_100","query_text":"I am ready to buy a replacement premium manual razor handle kit that features built-in multi-axis dynamic pivots. Where can I find it today?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Triggers targeted hardware structural conversion loops across digital and localized platforms."},
    {"query_code":"GROOM_BUY_MID_SKN_89_100","query_text":"I am looking at the men's skincare section. Should I select a clear non-foaming shave gel or an ultra-dense cooling cream to prevent skin tearing?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Audits localized chemical topical validation for premium skin protection gel components."},
    {"query_code":"GROOM_BUY_MID_ECO_90_100","query_text":"Where can I pick up a women's three-blade refillable manual body razor handle built with certified recycled ocean plastic components near me?","category":"Grooming","stage":"Ready to Buy","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Checks the distribution tracking metrics of sustainable sub-tiers inside mainstream retail networks."},
    {"query_code":"GROOM_BUY_NAR_CAS_91_100","query_text":"Will old three-blade system replacement cartridges click securely onto a modern five-blade flexible joint handle component?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Technical accuracy check verifying connector design backward-compatibility illusions."},
    {"query_code":"GROOM_BUY_NAR_VAL_92_100","query_text":"Where can I find authorized aftermarket replacement blades that are built to link perfectly with five-blade multi-axis handles?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures customer retention and conversion leak risks to third-party compatible structural components."},
    {"query_code":"GROOM_BUY_NAR_ENT_93_100","query_text":"I am about to purchase an active heated manual razor handle setup. Do I need to buy a separate wireless charging dock or is it bundled inside?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Validates bundle mapping parameters for complex technology setups right at final conversion loops."},
    {"query_code":"GROOM_BUY_NAR_SKN_94_100","query_text":"I am buying an intimate hair trimmer set. Do I need an alcohol-free soothing post-grooming cream to prevent immediate inflammation?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Audits cross-sell topical companion attachments for high-sensitivity cosmetic lines at checkouts."},
    {"query_code":"GROOM_BUY_NAR_VAL_45_100","query_text":"Where can I buy the two-blade sensitive guard manual cartridge head refills in a bulk eight-pack for the lowest online price?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures scraping fidelity for precise niche therapeutic consumable replacement SKUs."},
    {"query_code":"GROOM_RES_MID_SKN_96_100","query_text":"What manual razor systems are engineered specifically for shaving a completely bald head safely without nicking round contours?","category":"Grooming","stage":"Research","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates portfolio alignment for advanced multi-blade skull grooming sub-categories."},
    {"query_code":"GROOM_CMP_MID_SKN_97_100","query_text":"Is using a multi-blade pivoting cartridge razor or a dedicated electric foil skull clipper safer for preventing head bumps?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Balances manual hardware geometry against motorized tool formats across critical head-shaving demographics."},
    {"query_code":"GROOM_BUY_NAR_SKN_98_100","query_text":"Where can I purchase a pre-bundled kit containing an ultra-sensitive guard manual razor and a translucent cooling gel together today?","category":"Grooming","stage":"Ready to Buy","specificity":"Narrow","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Checks cross-category system tracking matching hardware units with specialized companion topicals."},
    {"query_code":"GROOM_CMP_MID_CAS_99_100","query_text":"What is the mechanical difference in blade durability between a basic manual travel disposable and an induction-heated manual razor system?","category":"Grooming","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Protects upscale electronic appliance hardware definitions from blending with cheap single-use plastic commodities."},
    {"query_code":"GROOM_RES_BRD_SKN_100_100","query_text":"What are the most recommended manual tool configurations for managing thick coarse beard lines if you cut easily?","category":"Grooming","stage":"Research","specificity":"Broad","persona":"Problem-Skin Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures unprompted hardware authority filters across independent grooming compliance and precision line-trimming vectors."},
]


def seed():
    inserted = updated = skipped = 0
    with session_factory() as session:
        for q in QUERIES:
            existing = session.query(SoaQuery)\
                .filter_by(query_code=q['query_code']).first()
            if existing:
                changed = any(getattr(existing, k, None) != v for k, v in q.items())
                if changed:
                    for k, v in q.items():
                        setattr(existing, k, v)
                    updated += 1
                else:
                    skipped += 1
            else:
                session.add(SoaQuery(**q))
                inserted += 1
        session.commit()
    print('━' * 44)
    print('Gillette 100 Seed Complete')
    print('━' * 44)
    print(f'Inserted: {inserted}')
    print(f'Updated:  {updated}')
    print(f'Skipped:  {skipped}')
    print(f'Total:    {inserted + updated + skipped}')

if __name__ == '__main__':
    seed()
