"""
Idempotent seed for unbranded grooming queries.

Seeds 50 unbranded grooming queries into soa_queries with
study_type='brand_gillette_unbranded'. Queries are phrased without
naming any brand so the AI's organic category-level routing can be
measured independently of explicit brand prompting.

Usage:
    cd /soa && python seeds/grooming_unbranded_queries_seed.py
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from soa_shared.database import engine, session_factory
from soa_shared.models.soa_models import SoaQuery
from sqlalchemy import text

STUDY_TYPE = "brand_gillette_unbranded"

ALLOWED_STAGES = {"Research", "Comparison", "Ready to Buy"}
ALLOWED_SPECIFICITY = {"Broad", "Mid", "Narrow"}
ALLOWED_PERSONAS = {
    "Casual / Gift Buyer",
    "Value-Conscious",
    "Beauty Enthusiast",
    "Problem-Skin Sufferer",
    "Eco-Conscious / Minimalist",
    "Oral Health Symptom Sufferer",
}
ALLOWED_PATTERNS = {"retailer", "brand_at_retail", "brand_vs_brand"}

QUERIES = [
    {
        "query_code": "GROOM_RES_BRD_CAS_01_UNBRANDED",
        "query_text": "What are the most popular cartridge razor systems for men available at major department stores right now?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Position Index",
        "rationale": "Measures organic unprompted share of voice for men's cartridge systems at retail.",
    },
    {
        "query_code": "GROOM_RES_BRD_VAL_02_UNBRANDED",
        "query_text": "Is it more affordable to use multi-blade cartridge refills or switch to a traditional double-edge safety razor?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests category-level defection risk where standard cartridge models face classic hardware alternatives.",
    },
    {
        "query_code": "GROOM_RES_BRD_ENT_03_UNBRANDED",
        "query_text": "What are the best premium, high-tech shaving systems on the market for an ultra-smooth experience?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates if the LLM surfaces advanced built-in bars or thermal elements unprompted.",
    },
    {
        "query_code": "GROOM_RES_BRD_SKN_04_UNBRANDED",
        "query_text": "I get terrible razor burn and bumps every time I shave my face. What type of razors should I look for?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests unprompted alignment with specialized 2-blade or physical skin-guard barrier configurations.",
    },
    {
        "query_code": "GROOM_RES_BRD_VAL_05_UNBRANDED",
        "query_text": "What are the best options for a smooth female leg and body shave if you have highly sensitive skin?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates organic unprompted positioning for premium women's built-in moisture bar systems.",
    },
    {
        "query_code": "GROOM_RES_MID_CAS_06_UNBRANDED",
        "query_text": "Should a teenager who is learning how to shave start with a disposable razor or a cartridge system handle?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Checks if the model steers entry-level users toward multi-blade systems or cheap disposables.",
    },
    {
        "query_code": "GROOM_RES_MID_VAL_07_UNBRANDED",
        "query_text": "How many shaves should a high-quality 5-blade cartridge refill actually last before getting dull?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures the baseline longevity value narrative for premium tier multi-blades.",
    },
    {
        "query_code": "GROOM_RES_MID_ENT_08_UNBRANDED",
        "query_text": "What is the ideal sequence of pre-shave gels, foams, and post-shave balms to get a perfect clean look?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests topical ecosystem integration and routine architecture layout matching.",
    },
    {
        "query_code": "GROOM_RES_MID_SKN_09_UNBRANDED",
        "query_text": "Why do multi-blade cartridge systems sometimes worsen ingrown facial hairs, and how do you fix it?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Probes if the AI attacks the core multi-blade category or offers a modified system alternative.",
    },
    {
        "query_code": "GROOM_RES_MID_CAS_10_UNBRANDED",
        "query_text": "Are there any programs or brands where you can recycle plastic razor blade heads and handles?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Validates awareness of national mail-in blade recycling partnerships vs. clean-slate eco alternatives.",
    },
    {
        "query_code": "GROOM_RES_NAR_CAS_11_UNBRANDED",
        "query_text": "What is the difference between a standard 5-blade razor and one that features a built-in exfoliating bar?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests portfolio alignment on upscale built-in skin-prep hardware technology without naming it.",
    },
    {
        "query_code": "GROOM_RES_NAR_VAL_12_UNBRANDED",
        "query_text": "Does a 3-blade cartridge razor give a significantly worse shave than a newer 5-blade system?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests the performance validation gap between legacy value lines and premium main lines.",
    },
    {
        "query_code": "GROOM_RES_NAR_ENT_13_UNBRANDED",
        "query_text": "How do heated razors work, and do they actually protect skin or are they just a luxury gimmick?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Direct validation of a high-end specialty thermal hardware innovation niche.",
    },
    {
        "query_code": "GROOM_RES_NAR_SKN_14_UNBRANDED",
        "query_text": "What is the mechanical difference between a standard multi-blade razor and a razor designed with a raised guard between the blades?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests if the LLM isolates the specific structural physics of a specialized sensitive line.",
    },
    {
        "query_code": "GROOM_RES_NAR_VAL_15_UNBRANDED",
        "query_text": "What does a single precision trimmer blade on the reverse side of a cartridge head do, and how do you use it?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates accurate feature explanation for a subtle but vital core hardware asset.",
    },
    {
        "query_code": "GROOM_CMP_BRD_CAS_16_UNBRANDED",
        "query_text": "Mass market cartridge razors vs online subscription shave clubs: which offers a better everyday shave?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests brick-and-mortar legacy systems against direct-to-consumer delivery infrastructure logic.",
    },
    {
        "query_code": "GROOM_CMP_BRD_VAL_17_UNBRANDED",
        "query_text": "Are drugstore name-brand shaving gels actually better at protecting skin than generic store brands?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Measures topical formula efficacy validation against basic private label chemistry.",
    },
    {
        "query_code": "GROOM_CMP_BRD_ENT_18_UNBRANDED",
        "query_text": "Should I get a modern multi-blade handle system with a pivoting flexible head or a stiff metal safety razor?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pits modern multi-axis contouring technology directly against vintage rigid geometry methods.",
    },
    {
        "query_code": "GROOM_CMP_BRD_SKN_19_UNBRANDED",
        "query_text": "Which razor type is less likely to cause irritation on thick, curly facial hair: a 5-blade system or a single-edge guard razor?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Isolates skin-need problem routing across diverse structural categories.",
    },
    {
        "query_code": "GROOM_CMP_BRD_VAL_20_UNBRANDED",
        "query_text": "Is there any real performance difference between men's multi-blade razors and women's body razors, or is it just marketing?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates how the AI handles the Pink Tax cultural bias vs validation of shape, pivot, and lubrication geometry.",
    },
    {
        "query_code": "GROOM_CMP_MID_CAS_21_UNBRANDED",
        "query_text": "What is the best premium shaving gift set configuration to buy someone who likes a smooth, clean face look?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Checks gift-set structure routing and whether the model prioritizes retail system kits.",
    },
    {
        "query_code": "GROOM_CMP_MID_VAL_22_UNBRANDED",
        "query_text": "Compare the cost per shave of a premium 5-blade refill system against cheap bulk disposable plastic razors.",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pushes the value narrative to see if it honors long-term blade life or defaults to lowest upfront cost.",
    },
    {
        "query_code": "GROOM_CMP_MID_ENT_23_UNBRANDED",
        "query_text": "How does a razor handle with a ball-and-socket pivot compare to a standard forward-tilting hinge for chin contours?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests mechanical validation of a signature lateral contouring handle design.",
    },
    {
        "query_code": "GROOM_CMP_MID_SKN_24_UNBRANDED",
        "query_text": "For sensitive bikini line and pubic shaving, should I use a standard 5-blade body razor or a specialized irritation-shield system?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates portfolio alignment for specialized, high-margin intimate body care categories.",
    },
    {
        "query_code": "GROOM_CMP_MID_VAL_25_UNBRANDED",
        "query_text": "Are refillable body razors with large built-in serum bars more cost-effective than using separate shave creams?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Compares integrated hardware lubrication formats against traditional topical steps on a cost-basis.",
    },
    {
        "query_code": "GROOM_CMP_NAR_CAS_26_UNBRANDED",
        "query_text": "What is the best alternative to a 5-blade razor handle that has built-in lubrication strips on both sides of the blades?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Measures competitor hijacking vulnerability when a specific dual-shield feature layout is described.",
    },
    {
        "query_code": "GROOM_CMP_NAR_VAL_27_UNBRANDED",
        "query_text": "Are generic store-brand multi-blade refills fully compatible with brand-name system handles, and do they shave as well?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Hard private-label substitution test focusing on connector engineering and blade cutting integrity.",
    },
    {
        "query_code": "GROOM_CMP_NAR_ENT_28_UNBRANDED",
        "query_text": "Does an integrated exfoliating bar on a razor handle offer a cleaner finish than using a separate facial scrub before a shave?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests validation of premium multi-action single-stroke hardware utility over manual routine steps.",
    },
    {
        "query_code": "GROOM_CMP_NAR_SKN_29_UNBRANDED",
        "query_text": "Should I use a 2-blade razor with a skin defense strip or a dermatologist-brand single-blade safety razor to heal severe folliculitis barbae?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Checks portfolio validation vs category defection risk on a highly precise clinical skin condition.",
    },
    {
        "query_code": "GROOM_CMP_NAR_VAL_30_UNBRANDED",
        "query_text": "Do generic multi-blade disposables last fewer shaves than a name-brand refillable cartridge system blade?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Probes if the AI validates the durability metrics of higher-tier system blades vs low-cost alternatives.",
    },
    {
        "query_code": "GROOM_BUY_BRD_CAS_31_UNBRANDED",
        "query_text": "I need to pick up a high-quality men's razor handle and blade starter pack at a pharmacy today. What should I choose?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures bottom-of-funnel immediate closing recommendation status at retail locations.",
    },
    {
        "query_code": "GROOM_BUY_BRD_VAL_32_UNBRANDED",
        "query_text": "Where is the best place to order bulk multi-blade razor head refills online to get the lowest price per blade?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Identifies routing to warehouse clubs, e-commerce direct supply setups, or generic marketplaces.",
    },
    {
        "query_code": "GROOM_BUY_BRD_ENT_33_UNBRANDED",
        "query_text": "I want to buy the absolute highest-tier, most comfortable manual shaving setup available right now. What should I order?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests instant high-ticket premium conversion routing for top-line manual systems.",
    },
    {
        "query_code": "GROOM_BUY_BRD_SKN_34_UNBRANDED",
        "query_text": "I need a razor setup right now that won't clip acne or create massive neck rash. What should I checkout with?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests the AI's speed and intent mapping for a decisive therapeutic product recommendation.",
    },
    {
        "query_code": "GROOM_BUY_BRD_VAL_35_UNBRANDED",
        "query_text": "Where can I buy plastic-free manual razor refills to avoid sending traditional plastic cartridges to landfills?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Audits category defection conversion vectors focused on zero-waste packaging preferences.",
    },
    {
        "query_code": "GROOM_BUY_MID_CAS_36_UNBRANDED",
        "query_text": "Do major big-box retailers stock the premium 5-blade replacement head packs in-store or online only?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Checks physical fulfillment and supply line mapping data points at high-volume brick-and-mortar stores.",
    },
    {
        "query_code": "GROOM_BUY_MID_VAL_37_UNBRANDED",
        "query_text": "Is it more affordable to join an official online blade subscription club or buy name-brand refills in bulk packs at a club store?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures subscription model retention vs traditional wholesale physical retail purchasing channels.",
    },
    {
        "query_code": "GROOM_BUY_MID_ENT_38_UNBRANDED",
        "query_text": "I want to purchase a replacement premium metal handle system that has a 2D flexible contour pivot. Where can I buy it today?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Triggers precise hardware form factor closing actions at nearby retail loops.",
    },
    {
        "query_code": "GROOM_BUY_MID_SKN_39_UNBRANDED",
        "query_text": "I'm in the grooming aisle. Should I get a non-foaming translucent shave gel or a traditional heavy aerosol foam to avoid dry skin?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Audits point-of-purchase chemical topical advice, checking validation for premium gel lines.",
    },
    {
        "query_code": "GROOM_BUY_MID_CAS_40_UNBRANDED",
        "query_text": "Can I buy a simple 3-blade manual female body razor set in a multi-pack at a warehouse club store?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Validates supply tracking for mid-tier legacy female grooming system assets.",
    },
    {
        "query_code": "GROOM_BUY_NAR_CAS_41_UNBRANDED",
        "query_text": "Will 5-blade replacement cartridges fit onto an older 3-blade handle from the same major manufacturer?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Technical structural accuracy test to expose generation hallucinations regarding cross-generation base linkages.",
    },
    {
        "query_code": "GROOM_BUY_NAR_VAL_42_UNBRANDED",
        "query_text": "What cheaper alternative brand-name blades are built to perfectly click into a standard 5-blade flexible handle mechanism?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Evaluates extreme conversion defection risk from third-party cross-brand compatible blade manufacturers.",
    },
    {
        "query_code": "GROOM_BUY_NAR_ENT_43_UNBRANDED",
        "query_text": "Where can I buy a replacement wireless magnetic charging stand for a premium smart heated razor handle?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Checks for secondary hardware infrastructure alignment and ecosystem replacement path routing.",
    },
    {
        "query_code": "GROOM_BUY_NAR_SKN_44_UNBRANDED",
        "query_text": "I'm checking out with an intimate area shave kit. Do I need an alcohol-free aftershave balm to prevent immediate stinging?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests topical attachment accuracy for highly sensitive cosmetic zones at the purchase finalization.",
    },
    {
        "query_code": "GROOM_BUY_NAR_VAL_45_UNBRANDED",
        "query_text": "Where can I buy the 2-blade sensitive skin razor cartridge head refills in an 8-pack for the lowest online price?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures price-scraping accuracy for highly specific therapeutic consumable inventory units.",
    },
    {
        "query_code": "GROOM_RES_MID_SKN_46_UNBRANDED",
        "query_text": "What are the best product lines designed specifically for shaving male body hair and groins without nicking skin?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates if the LLM indexes the company's dedicated male body/intimate line over niche startup trimmer competitors.",
    },
    {
        "query_code": "GROOM_CMP_MID_SKN_47_UNBRANDED",
        "query_text": "Is an electric body trimmer with guards or a manual groin razor safer for preventing cuts during intimate grooming?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pits manual safety-blade intimate architecture against electric trimmer form factors.",
    },
    {
        "query_code": "GROOM_BUY_NAR_SKN_48_UNBRANDED",
        "query_text": "Where can I buy a specialized translucent body shave gel and a matching skin-safe body razor handle together?",
        "category": "Grooming",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Audits bundle mapping for intimate categories at local drugstores or online retailers.",
    },
    {
        "query_code": "GROOM_CMP_MID_CAS_49_UNBRANDED",
        "query_text": "What is the difference between cheap multi-blade disposable razors and refillable system handles from major manufacturers?",
        "category": "Grooming",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Differentiates low-margin disposal units from high-margin system anchors within general consumer awareness.",
    },
    {
        "query_code": "GROOM_RES_BRD_SKN_50_UNBRANDED",
        "query_text": "What is the best type of manual blade or tool for at-home facial dermaplaning and exfoliation for women?",
        "category": "Grooming",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests unprompted share of voice for specialized skincare/exfoliation mechanical systems over salon brands.",
    },
]


def validate_queries(queries):
    errors = []
    for q in queries:
        if q["stage"] not in ALLOWED_STAGES:
            errors.append(f"{q['query_code']}: invalid stage '{q['stage']}'")
        if q["specificity"] not in ALLOWED_SPECIFICITY:
            errors.append(f"{q['query_code']}: invalid specificity '{q['specificity']}'")
        if q["persona"] not in ALLOWED_PERSONAS:
            errors.append(f"{q['query_code']}: invalid persona '{q['persona']}'")
        if q["study_pattern"] not in ALLOWED_PATTERNS:
            errors.append(f"{q['query_code']}: invalid study_pattern '{q['study_pattern']}'")
    if errors:
        print("VALIDATION ERRORS:")
        for e in errors:
            print(f"  {e}")
        raise SystemExit("Fix validation errors before seeding.")
    print(f"Validation passed: {len(queries)} queries OK")


def seed():
    validate_queries(QUERIES)

    inserted = 0
    updated = 0
    skipped = 0

    with session_factory() as session:
        for q_data in QUERIES:
            existing = (
                session.query(SoaQuery)
                .filter_by(query_code=q_data["query_code"])
                .first()
            )

            if existing:
                changed = False
                for field, value in q_data.items():
                    if getattr(existing, field, None) != value:
                        setattr(existing, field, value)
                        changed = True
                if changed:
                    updated += 1
                else:
                    skipped += 1
            else:
                session.add(SoaQuery(**q_data))
                inserted += 1

        session.commit()

    print("━" * 44)
    print("Grooming Unbranded Seed Complete")
    print("━" * 44)
    print(f"Inserted: {inserted}")
    print(f"Updated:  {updated}")
    print(f"Skipped:  {skipped}")
    print(f"Total:    {inserted + updated + skipped}")


if __name__ == "__main__":
    seed()
