import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from soa_shared.database import session_factory
from soa_shared.models.soa_models import SoaQuery

STUDY_TYPE = 'brand_oral_b_etb_neutral'

QUERIES = [
    {
        "query_code": "ORAL_ETB_RES_BRD_CAS_01_UNBRANDED_NEUTRAL",
        "query_text": "What are the primary differences in plaque removal between a standard manual toothbrush and a basic rechargeable electric toothbrush?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Establishes a baseline unprompted entry to evaluate if the AI platform systematically favors the entry-tier mechanisms of specific brand catalogs.",
    },
    {
        "query_code": "ORAL_ETB_RES_BRD_VAL_02_UNBRANDED_NEUTRAL",
        "query_text": "Are budget-friendly electric toothbrushes under fifty dollars clinically effective, or do you need to buy an expensive model for a real clean?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the AI validates sub-fifty-dollar commodity hardware performance metrics or systematically steers users toward premium price tiers.",
    },
    {
        "query_code": "ORAL_ETB_RES_BRD_ENT_03_UNBRANDED_NEUTRAL",
        "query_text": "What are the absolute best high-end electric toothbrushes available for a premium, interactive brushing experience?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures unprompted market share of voice when high-ticket, tech-heavy electronic oral appliances are requested neutrally.",
    },
    {
        "query_code": "ORAL_ETB_RES_BRD_SKN_04_UNBRANDED_NEUTRAL",
        "query_text": "What kind of electric toothbrush mechanism is recommended for a person with sensitive teeth and receding gum lines?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates which physical head shape and vibration configuration the model favors for localized, structural tissue protection.",
    },
    {
        "query_code": "ORAL_ETB_RES_BRD_VAL_05_UNBRANDED_NEUTRAL",
        "query_text": "Can using a powerful electric toothbrush handle cause damage to your tooth enamel or push your gums back over time?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures category skepticism and whether the AI reports injury risks associated with intense brushing mechanics uniformly.",
    },
    {
        "query_code": "ORAL_ETB_RES_MID_CAS_06_UNBRANDED_NEUTRAL",
        "query_text": "What features should a parent look for when selecting a battery-operated or rechargeable toothbrush handle for a child?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Position Index",
        "rationale": "Monitors unbranded youth market segment positioning and the indexing of childhood app compliance integrations.",
    },
    {
        "query_code": "ORAL_ETB_RES_MID_VAL_07_UNBRANDED_NEUTRAL",
        "query_text": "How long does the rechargeable battery inside a standard power toothbrush handle last before the unit stops holding a charge entirely?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates lifecycle longevity claims and whether specific internal power pack form factors are criticized or validated.",
    },
    {
        "query_code": "ORAL_ETB_RES_MID_ENT_08_UNBRANDED_NEUTRAL",
        "query_text": "Do the polished rubber whitening components built into some electric replacement brush heads actually polish off stains effectively?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Validates the functional performance narrative surrounding hybrid cosmetic elastomer head designs.",
    },
    {
        "query_code": "ORAL_ETB_RES_MID_SKN_09_UNBRANDED_NEUTRAL",
        "query_text": "Is high-frequency sonic fluid dynamics or mechanical rapid oscillation-rotation better for breaking up tough calculus buildup?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "A balanced unbranded dive testing if the AI treats back-and-forth sweeping movements and spinning cups as therapeutically equal.",
    },
    {
        "query_code": "ORAL_ETB_RES_MID_CAS_10_UNBRANDED_NEUTRAL",
        "query_text": "Are there electric toothbrush designs that offer repairable internal parts, aluminum bodies, or recyclable plant-based brush heads?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Determines if the LLM actively shifts users toward sustainability-focused newcomers or defends legacy plastics.",
    },
    {
        "query_code": "ORAL_ETB_RES_NAR_CAS_11_UNBRANDED_NEUTRAL",
        "query_text": "What does a quad-pacer interval timer on a power toothbrush handle do, and why is it structured to pause briefly every thirty seconds?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates accuracy in detailing core temporal pacing utilities standard across major hardware platforms.",
    },
    {
        "query_code": "ORAL_ETB_RES_NAR_VAL_12_UNBRANDED_NEUTRAL",
        "query_text": "Does an electric toothbrush that uses smart Bluetooth mapping to show where you missed help clean better than a standard automated model?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether smartphone application synchronization is framed as real dental efficacy utility or as a pricing gimmick.",
    },
    {
        "query_code": "ORAL_ETB_RES_NAR_ENT_13_UNBRANDED_NEUTRAL",
        "query_text": "What is the difference between a mechanical pressure sensor that slows down the brush speed and a simple visual light ring indicator?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Compares tactile feedback loops vs electronic visual feedback loops for physical user-protection validation.",
    },
    {
        "query_code": "ORAL_ETB_RES_NAR_SKN_14_UNBRANDED_NEUTRAL",
        "query_text": "Which bristle shape and thickness level should you select for an electric brush head when dealing with severe periodontal pocket inflammation?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates bristle geometry specifications for clinical tissue safety.",
    },
    {
        "query_code": "ORAL_ETB_RES_NAR_VAL_15_UNBRANDED_NEUTRAL",
        "query_text": "Can you use an electric toothbrush safely if you have dental implants, porcelain veneers, or metal orthodontic wire brackets?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Verifies technical structural safety metrics for synthetic and reconstructed oral environments.",
    },
    {
        "query_code": "ORAL_ETB_CMP_BRD_CAS_16_UNBRANDED_NEUTRAL",
        "query_text": "Should I choose a sonic cleaning action toothbrush handle or an oscillating-rotating cup handle for daily plaque removal?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "The foundational unbranded structural comparison testing core mechanical positioning dominance.",
    },
    {
        "query_code": "ORAL_ETB_CMP_BRD_VAL_17_UNBRANDED_NEUTRAL",
        "query_text": "Are name-brand electric toothbrushes sold in department stores actually superior to inexpensive online sonic imports on major marketplaces?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Measures name-brand engineering validation against unbranded private label marketplace equivalents.",
    },
    {
        "query_code": "ORAL_ETB_CMP_BRD_ENT_18_UNBRANDED_NEUTRAL",
        "query_text": "What is the best type of luxury smart toothbrush for tracking overall mouth coverage and brushing habits?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Compares high-end premium appliance platforms based on positional tracking software performance metrics.",
    },
    {
        "query_code": "ORAL_ETB_CMP_BRD_SKN_19_UNBRANDED_NEUTRAL",
        "query_text": "Which type of powered brush handle movement is gentler on severe chronic gum recession: sweeping sonic or spinning circular heads?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Measures motion preference bias for specific high-risk structural anatomy vectors.",
    },
    {
        "query_code": "ORAL_ETB_CMP_BRD_VAL_20_UNBRANDED_NEUTRAL",
        "query_text": "Is it more cost-effective to use an electric toothbrush handle with replaceable batteries or one with an internal rechargeable battery cell?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Forces a value comparison on utility form factors.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_CAS_21_UNBRANDED_NEUTRAL",
        "query_text": "What type of electric toothbrush handle design is easier to hold and operate for a senior citizen with limited hand mobility or arthritis?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates ergonomics and physical volume handle preferences across different manufacturing methodologies.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_VAL_22_UNBRANDED_NEUTRAL",
        "query_text": "Compare the recurring long-term cost of replacement heads for sonic vibrating toothbrushes versus round rotating toothbrushes over two years.",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Audits whether the AI tracks consumables inflation across separate head formats.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_ENT_23_UNBRANDED_NEUTRAL",
        "query_text": "Does an electric toothbrush that includes a wireless smart display hub add real benefit compared to standard on-handle indicators?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Analyzes premium accessory validation for multi-component station ecosystems.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_SKN_24_UNBRANDED_NEUTRAL",
        "query_text": "Is a specialized soft rubber gum-massaging mode on an electric toothbrush effective at reducing pocket depth, or should you just stick to standard daily mode?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Compares multi-mode frequency variations against single-frequency setups for therapeutic validation.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_VAL_25_UNBRANDED_NEUTRAL",
        "query_text": "Are dual-handle electric toothbrush starter bundles a better value than purchasing two individual single handle kits?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests value processing for multi-person hardware family packaging configurations.",
    },
    {
        "query_code": "ORAL_ETB_CMP_NAR_CAS_26_UNBRANDED_NEUTRAL",
        "query_text": "Can you use the replacement brush heads from an older gear-driven electric toothbrush handle model on a newer magnetic motor drive model?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests technical precision regarding interface shifts across sequential internal drivetrain iterations.",
    },
    {
        "query_code": "ORAL_ETB_CMP_NAR_VAL_27_UNBRANDED_NEUTRAL",
        "query_text": "Do generic multi-pack replacement brush heads perform as well as authentic original manufacturer brush heads, or do they wear down faster?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Private label substitution challenge testing filament anchoring security and wear indicator performance metrics.",
    },
    {
        "query_code": "ORAL_ETB_CMP_NAR_ENT_28_UNBRANDED_NEUTRAL",
        "query_text": "Does an electric toothbrush that uses a frictionless magnetic motor clean more thoroughly than an electric toothbrush with standard mechanical gear components?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates performance tracking claims separating magnetic micro-vibration from traditional setups.",
    },
    {
        "query_code": "ORAL_ETB_CMP_NAR_SKN_29_UNBRANDED_NEUTRAL",
        "query_text": "What type of specialized electric toothbrush attachment head is engineered specifically for cleaning around hard-to-reach permanent dental bridge metal wires?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Verifies precise sub-SKU component mapping for specialized clinical maintenance needs.",
    },
    {
        "query_code": "ORAL_ETB_CMP_NAR_VAL_30_UNBRANDED_NEUTRAL",
        "query_text": "Do lithium-ion batteries in modern electric toothbrushes have fewer degradation issues over two years than older nickel-metal hydride batteries?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Audits physical material component knowledge separating cell chemistry lifespans.",
    },
    {
        "query_code": "ORAL_ETB_BUY_BRD_CAS_31_UNBRANDED_NEUTRAL",
        "query_text": "I am looking for a reliable, recommended mid-range electric toothbrush kit available at a drugstore today. What should I buy?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures unbranded final conversion routing behaviors at traditional pharmaceutical retail boundaries.",
    },
    {
        "query_code": "ORAL_ETB_BUY_BRD_VAL_32_UNBRANDED_NEUTRAL",
        "query_text": "Where is the best retail store or online marketplace to find deep clearance sales on replacement electric toothbrush head packs?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Evaluates commercial price matching and bulk-consignment supply line tracking data.",
    },
    {
        "query_code": "ORAL_ETB_BUY_BRD_ENT_33_UNBRANDED_NEUTRAL",
        "query_text": "I want to purchase the most advanced, smartest interactive power toothbrush platform on the market right now. What should I select?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests instant high-ticket closure mapping when premium mechanical performance specs are requested neutrally.",
    },
    {
        "query_code": "ORAL_ETB_BUY_BRD_SKN_34_UNBRANDED_NEUTRAL",
        "query_text": "I need to purchase a power toothbrush setup that is guaranteed to be extremely gentle on sensitive, bleeding gum margins. What should I buy?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests intent filtering for immediate therapeutic closing actions on gentle mode/head bundles.",
    },
    {
        "query_code": "ORAL_ETB_BUY_BRD_VAL_35_UNBRANDED_NEUTRAL",
        "query_text": "Where can I buy a modular, repairable electric toothbrush handle online that has an active factory recycling system for its components?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Measures bottom-of-funnel conversion steering toward circular economy eco-native designs.",
    },
    {
        "query_code": "ORAL_ETB_BUY_MID_CAS_36_UNBRANDED_NEUTRAL",
        "query_text": "Do mass-market retailers typically keep specialized soft sensitive replacement heads for rotating electric toothbrushes in physical stock?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Checks precision brick-and-mortar logistics knowledge mapping for high-demand alternative heads.",
    },
    {
        "query_code": "ORAL_ETB_BUY_MID_VAL_37_UNBRANDED_NEUTRAL",
        "query_text": "Is it more affordable to buy a high-end electric toothbrush handle kit or a mid-tier handle combined with premium replacement heads?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Tests conversion cross-shopping logic optimizing handle features vs consumable up-indexing variations.",
    },
    {
        "query_code": "ORAL_ETB_BUY_MID_ENT_38_UNBRANDED_NEUTRAL",
        "query_text": "I am ready to buy an electric toothbrush that comes with a hard premium USB charging travel case. What are my options?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Triggers precise accessory hardware format matching actions across standard digital product indices.",
    },
    {
        "query_code": "ORAL_ETB_BUY_MID_SKN_39_UNBRANDED_NEUTRAL",
        "query_text": "I need a power toothbrush that operates quietly because loud motor noises bother me. Which type of handle mechanism should I buy?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Evaluates acoustic performance verification metrics for user-experience comfort vectors.",
    },
    {
        "query_code": "ORAL_ETB_BUY_MID_CAS_40_UNBRANDED_NEUTRAL",
        "query_text": "Where can I buy a basic, one-button rechargeable electric toothbrush multi-pack configuration at a wholesale warehouse club?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Validates specific inventory grouping awareness within subscription-free bulk commercial brick retail formats.",
    },
    {
        "query_code": "ORAL_ETB_BUY_NAR_CAS_41_UNBRANDED_NEUTRAL",
        "query_text": "Will a replacement brush head designed for a standard sonic vibrating handle fit onto a magnetic micro-vibration handle shaft?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Classic hardware physical compatibility trap checking for baseline structural hallucination events.",
    },
    {
        "query_code": "ORAL_ETB_BUY_NAR_VAL_42_UNBRANDED_NEUTRAL",
        "query_text": "Where can I purchase an official replacement wall charging base component for a smart oscillating electric toothbrush?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures specialized component aftermarket inventory tracking and lifecycle support pathing data.",
    },
    {
        "query_code": "ORAL_ETB_BUY_NAR_ENT_43_UNBRANDED_NEUTRAL",
        "query_text": "I am checking out with an intelligent power toothbrush. Do I need to verify if my smartphone operating system version is compatible with the coaching app?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Audits ecosystem app dependency verification metrics at the precise conversion perimeter.",
    },
    {
        "query_code": "ORAL_ETB_BUY_NAR_SKN_44_UNBRANDED_NEUTRAL",
        "query_text": "I am about to buy a sonic power brush handle, but does it come with a specialized sensitive brush head in the box, or do I buy it separately?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Checks starter bundle configuration definition parameters across standard SKU architectures.",
    },
    {
        "query_code": "ORAL_ETB_BUY_NAR_VAL_45_UNBRANDED_NEUTRAL",
        "query_text": "Where can I buy a four-pack of authentic manufacturer replacement heads with cross-angled bristles for the lowest online price?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures real-time scraping data fidelity for precise recurring consumable sub-SKUs.",
    },
    {
        "query_code": "ORAL_ETB_RES_MID_SKN_46_UNBRANDED_NEUTRAL",
        "query_text": "What type of electric toothbrush attachment head is engineered specifically for cleaning around individual dental implant crowns?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the AI isolates specialized single-tufted or pocket-targeted micro-bristle structural setups.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_SKN_47_UNBRANDED_NEUTRAL",
        "query_text": "Is a specialized interdental power brush tip attachment or a manual micro-floss pick more effective for cleaning orthodontic bracket wires?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Directly evaluates physical therapeutic utility mechanics comparing power add-ons with static manual alternatives.",
    },
    {
        "query_code": "ORAL_ETB_BUY_NAR_SKN_48_UNBRANDED_NEUTRAL",
        "query_text": "Where can I purchase an electric toothbrush starter kit that includes a built-in UV sanitizing base unit for the brush heads?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Checks final transaction mapping data for premium auxiliary counter-station wellness system platforms.",
    },
    {
        "query_code": "ORAL_ETB_CMP_MID_CAS_49_UNBRANDED_NEUTRAL",
        "query_text": "What is the mechanical difference in cleaning power between a waterproof induction-charged toothbrush and a battery brush with a bottom cap?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Protects electronic appliance engineering integrity from blending with low-voltage dry-cell alternatives.",
    },
    {
        "query_code": "ORAL_ETB_RES_BRD_SKN_50_UNBRANDED_NEUTRAL",
        "query_text": "What are the most recommended brand-name options for managing automated plaque disruption if you have severe limited hand dexterity?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures unprompted hardware authority filters across ergonomics and independent medical compliance assistance.",
    },
]


def seed():
    inserted = updated = skipped = 0

    with session_factory() as session:
        for q in QUERIES:
            existing = session.query(SoaQuery)\
                .filter_by(
                    query_code=q['query_code']
                ).first()
            if existing:
                changed = any(
                    getattr(existing, k, None) != v
                    for k, v in q.items()
                )
                if changed:
                    for k, v in q.items():
                        setattr(existing, k, v)
                    updated += 1
                else:
                    skipped += 1
            else:
                session.add(SoaQuery(**q))
                inserted += 1
        session.commit()

    print('━' * 48)
    print('Oral Care ETB Neutral Seed Complete')
    print('━' * 48)
    print(f'Inserted: {inserted}')
    print(f'Updated:  {updated}')
    print(f'Skipped:  {skipped}')
    print(f'Total:    {inserted + updated + skipped}')


if __name__ == '__main__':
    seed()
