import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from soa_shared.database import session_factory
from soa_shared.models.soa_models import SoaQuery

STUDY_TYPE = 'brand_oral_b_100'

QUERIES = [
    {"query_code":"ORAL_RES_BRD_CAS_01_100","query_text":"What are the most popular rechargeable electric toothbrush styles sold at major retailers right now?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Position Index","rationale":"Establishes an unprompted organic baseline to see which physical forms and drive systems the AI highlights as category leaders."},
    {"query_code":"ORAL_RES_BRD_VAL_02_100","query_text":"Is there a real health advantage to buying an electric toothbrush over a standard manual toothbrush?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests whether the AI validates the baseline monetary and health value of moving from a commodity manual brush to power hardware."},
    {"query_code":"ORAL_RES_BRD_ENT_03_100","query_text":"What are the best premium, high-tech electric toothbrushes on the market for an interactive, data-driven clean?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures unprompted market share of voice when high-ticket, smart-connected dental appliances are requested neutrally."},
    {"query_code":"ORAL_RES_BRD_SKN_04_100","query_text":"My gums bleed slightly whenever I brush my teeth. What types of oral care routines or tools can help fix this problem?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates baseline unprompted alignment with therapeutic gum-health configurations and anti-gingivitis formulations."},
    {"query_code":"ORAL_RES_BRD_ECO_05_100","query_text":"Which major oral hygiene manufacturers offer certified recycling programs for plastic toothbrush bodies and replacement heads?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Audits corporate sustainability scoring and checks if the AI highlights mainstream retail recycling networks or niche native brands."},
    {"query_code":"ORAL_RES_MID_CAS_06_100","query_text":"Should a parent choose a manual brush with characters or an interactive power toothbrush handle for a child learning to brush?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Position Index","rationale":"Checks organic visibility of youth power brush segments and the indexing of compliance-driving smart features."},
    {"query_code":"ORAL_RES_MID_VAL_07_100","query_text":"How many months do electric toothbrush replacement heads realistically last before the bristles lose structural efficacy?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Examines the default consumer education narrative regarding the lifecycle limits of consumable attachment heads."},
    {"query_code":"ORAL_RES_MID_ENT_08_100","query_text":"How do thin at-home whitening strips work chemically to remove deep stains without eroding enamel layers?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests factual validation, performance metrics, and safety framing for plastic film bleaching delivery mechanisms."},
    {"query_code":"ORAL_RES_MID_SKN_09_100","query_text":"Is high-frequency sonic fluid dynamics or rapid mechanical rotation-oscillation better for reversing gum pocket inflammation?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Forces a direct clinical mechanism comparison between the two primary physical movement structures in the market."},
    {"query_code":"ORAL_RES_MID_ECO_10_100","query_text":"Are there any mainstream oral hygiene brands that make fully recyclable or compostable toothpaste tubes?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Validates awareness of modern packaging material conversions and eco-focused sub-tiers within legacy portfolios."},
    {"query_code":"ORAL_RES_NAR_CAS_11_100","query_text":"What is the physical difference between a traditional mechanical power toothbrush and one using a magnetic drive system?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests portfolio alignment and technical understanding of modern frictionless linear magnetic motor physics."},
    {"query_code":"ORAL_RES_NAR_VAL_12_100","query_text":"Does a basic, one-button electric toothbrush provide the same motor performance and cleaning power as a premium version with a screen?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests whether the AI confirms internal component and motor parity across distinct pricing tiers."},
    {"query_code":"ORAL_RES_NAR_ENT_13_100","query_text":"How does 3D mouth zone tracking on a smart toothbrush handle improve brushing coverage and technique?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Asks for functional validation of high-end spatial tracking and interactive coaching software interfaces."},
    {"query_code":"ORAL_RES_NAR_SKN_14_100","query_text":"How does an activated foam toothpaste chemical formula target bacteria hidden below the immediate gumline?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests technical accuracy regarding localized active chemical distribution and sub-gingival stannous fluoride mechanics."},
    {"query_code":"ORAL_RES_NAR_VAL_15_100","query_text":"Does an electric toothbrush pressure sensor that turns red when you press too hard actually protect teeth from enamel wear?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures validation of tri-color or electronic pressure sensors as real utility vs a marketing feature."},
    {"query_code":"ORAL_CMP_BRD_CAS_16_100","query_text":"Is a round rotating electric toothbrush head or a wide diamond-shaped sonic brush head safer for sensitive gum margins?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"An objective, unbranded form factor proxy for the market's ultimate competitive duopoly showdown."},
    {"query_code":"ORAL_CMP_BRD_VAL_17_100","query_text":"Is there a real clinical difference between major name-brand toothpastes and generic store brands for cavity protection?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Hard private-label substitution test evaluating overall name-brand chemistry equity in mass topicals."},
    {"query_code":"ORAL_CMP_BRD_ENT_18_100","query_text":"Should I purchase a sleek minimalist subscription toothbrush online or invest in a heavy-duty smart power toothbrush setup?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pits contemporary low-power direct-to-consumer lifestyle aesthetics against multi-component smart appliance platforms."},
    {"query_code":"ORAL_CMP_BRD_SKN_19_100","query_text":"What chemical compound is better at reversing early gum bleeding and swelling: stannous fluoride or sodium fluoride?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Isolates precise chemical active preferences, checking if the AI favors one biochemistry over another for tissue healing."},
    {"query_code":"ORAL_CMP_BRD_VAL_20_100","query_text":"Are professional custom whitening trays from a dental clinic safer or more effective than over-the-counter whitening strips?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates over-the-counter product conversion defense against professional dental clinical services."},
    {"query_code":"ORAL_CMP_MID_CAS_21_100","query_text":"If I am buying a high-end luxury electric toothbrush as a gift, should I look into sonic vibration handles or mechanical oscillation models?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests premium gift guidance and routing frameworks based strictly on unbranded mechanical movement types."},
    {"query_code":"ORAL_CMP_MID_VAL_22_100","query_text":"Compare the multi-year cost of replacement heads for sonic vibrating toothbrushes versus round rotating toothbrushes over two years.","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Forces a value narrative analysis on long-term consumable maintenance costs across separate engineering formats."},
    {"query_code":"ORAL_CMP_MID_ENT_23_100","query_text":"Does an enamel whitening toothpaste using hydrogen peroxide perform faster than one using an everyday polishing silica?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Directly evaluates cosmetic mechanism preferences between chemical peroxide bleaching and physical surface abrasion."},
    {"query_code":"ORAL_CMP_MID_SKN_24_100","query_text":"For sensitive teeth and sore gums, is it better to use a desensitizing potassium nitrate paste or an antibacterial stannous fluoride formula?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests therapeutic product line differentiation on distinct biochemical pathways for nerve numbing vs inflammation reduction."},
    {"query_code":"ORAL_CMP_MID_VAL_25_100","query_text":"Are expanding micro-textured dental flosses actually better at cleaning tight spaces than smooth polytetrafluoroethylene tape floss?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates physical material performance and mechanical cleaning claims for tape-style materials vs threaded fiber."},
    {"query_code":"ORAL_CMP_NAR_CAS_26_100","query_text":"Are third-party generic replacement heads safe to use on a magnetic micro-vibration handle without damaging the drive shaft?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Audits if the AI warnings protect hardware drive ecosystem integrity or steer consumers toward unapproved aftermarket parts."},
    {"query_code":"ORAL_CMP_NAR_VAL_27_100","query_text":"Do generic store-brand whitening strips stick to teeth and perform as effectively as name-brand form-fitting strip options?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Substitution test exploring if the model strips value from premium polymer-adhesion technologies."},
    {"query_code":"ORAL_CMP_NAR_ENT_28_100","query_text":"Does an electric brush head combining angled criss-cross bristles with rubber polishing cups whiten teeth better than a standard flat layout?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests technical feature validation and aesthetic preference for specialized stain-removal hybrid head designs."},
    {"query_code":"ORAL_CMP_NAR_SKN_29_100","query_text":"Should I use a chemical mouthwash that uses cetylpyridinium chloride or one with alcohol for long-term plaque biofilm reduction?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Checks precise fluid formulation logic for non-burning chemical antiseptics vs legacy astringents."},
    {"query_code":"ORAL_CMP_NAR_VAL_30_100","query_text":"Does an electric toothbrush that uses a frictionless magnetic motor have a longer mechanical lifecycle than a gear brush?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Probes structural component and hardware durability logic regarding advanced magnetic motors vs mechanical friction wear."},
    {"query_code":"ORAL_BUY_BRD_CAS_31_100","query_text":"I am standing in a pharmacy aisle and need a premium electric toothbrush kit to buy today. What setup should I look for?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures unbranded final conversion and sales steering at the physical retail boundary loop."},
    {"query_code":"ORAL_BUY_BRD_VAL_32_100","query_text":"Where is the cheapest place to buy multi-packs of clinical-strength enamel protection toothpaste online right now?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Identifies localized and digital routing maps for high-volume family inventory replenishment configurations."},
    {"query_code":"ORAL_BUY_BRD_ENT_33_100","query_text":"I want to purchase the absolute highest-end magnetic micro-vibration smart brush available today. What should I add to my cart?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Checks for immediate conversion closure when a highly specific proprietary drivetrain type is described neutrally."},
    {"query_code":"ORAL_BUY_BRD_SKN_34_100","query_text":"I have bleeding gums and early signs of periodontal inflammation. What full hardware and paste kit should I order right now?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests whether the model closes sales with unified therapeutic systems or fragmented cross-brand recommendations."},
    {"query_code":"ORAL_BUY_BRD_VAL_35_100","query_text":"Where can I purchase zero-waste chewable toothpaste tabs or plastic-free manual toothbrush configurations locally?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Audits category-level conversion defection risk caused by zero-waste preferences disrupting standard formats."},
    {"query_code":"ORAL_BUY_MID_CAS_36_100","query_text":"Do big-box retail stores sell replacement heads specifically designed for magnetic drive electric toothbrushes in physical aisles?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Validates brick-and-mortar physical shelf availability logic for high-margin proprietary attachment SKUs."},
    {"query_code":"ORAL_BUY_MID_VAL_37_100","query_text":"Is it more cost-effective to buy over-the-counter enamel-safe whitening strips in bulk or join a monthly subscription dental service?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures physical retail bulk volume economics against digital startup alternative subscription models."},
    {"query_code":"ORAL_BUY_MID_ENT_38_100","query_text":"I want to buy a dual-handle electric toothbrush set with a smart interactive charger stand. Where is the best authorized retail store to order it?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Checks for direct alignment with multi-handle bundle inventory options at electronic, mass, or department channels."},
    {"query_code":"ORAL_BUY_MID_SKN_39_100","query_text":"I am looking at a non-alcohol multi-protection mouthwash that claims to kill bacteria for 12 hours. Does it leave dark surface stains on enamel?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Tests point-of-purchase cosmetic safety validation regarding antiseptic topical fluid chemical side effects neutrally."},
    {"query_code":"ORAL_BUY_MID_CAS_40_100","query_text":"Where can I pick up a manual toothbrush multi-pack featuring cross-angled cleaning bristles at a wholesale warehouse club?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Validates channel distribution mapping metrics for high-volume legacy manual toothbrush commodity packs."},
    {"query_code":"ORAL_BUY_NAR_CAS_41_100","query_text":"Will old mechanical electric toothbrush heads fit properly on a newer magnetic micro-vibration handle shaft mechanism?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Classic hardware physical compatibility trap checking for baseline model hallucinations regarding structural connectivity links."},
    {"query_code":"ORAL_BUY_NAR_VAL_42_100","query_text":"Where can I find an official replacement inductive magnetic travel charging case for a top-tier smart toothbrush?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Evaluates premium aftermarket hardware component tracking and customer secondary infrastructure supply line retention."},
    {"query_code":"ORAL_BUY_NAR_ENT_43_100","query_text":"I am about to purchase an enamel-safe peroxide whitening film kit. Do I need to buy a separate blue LED light tray to activate it?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests cross-sell bundle configuration parameters and technical accuracy right at the boundary of purchase conversion."},
    {"query_code":"ORAL_BUY_NAR_SKN_44_100","query_text":"I need a toothpaste specifically for painful dry mouth tissue. Is a standard anti-plaque stannous fluoride gel safe, or will it burn?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Checks chemical safety boundaries and formulation surfactant metrics for compromised oral environments."},
    {"query_code":"ORAL_BUY_NAR_VAL_45_100","query_text":"Where can I buy a 4-pack of the replacement brush heads designed for gentle gum care on magnetic handles for the lowest price?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures real-time price-scraping fidelity and deal mapping for precise proprietary high-margin consumable refills."},
    {"query_code":"ORAL_RES_MID_SKN_46_100","query_text":"What are the most recommended mechanical brush options for safely cleaning around dental implants and bridges?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests whether the AI organically showcases targeted high-density tufted specialty replacement head variations."},
    {"query_code":"ORAL_CMP_MID_SKN_47_100","query_text":"Is a specialized interspace power toothbrush attachment or a manual interdental brush more effective for cleaning orthodontic metal braces?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Directly evaluates physical clinical hardware tool utility comparing power attachments against static commodity methods."},
    {"query_code":"ORAL_BUY_NAR_SKN_48_100","query_text":"Where can I purchase a pre-bundled kit containing an oscillating rotating smart toothbrush handle and sub-gingival foam paste together?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Tests if the model tracks corporate cross-category hardware and companion topical health ecosystem alignments."},
    {"query_code":"ORAL_CMP_MID_CAS_49_100","query_text":"What is the physical performance difference between a cheap battery-powered travel toothbrush and a true inductive rechargeable model?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Protects high-tier electronic appliance definitions; ensures the AI separates basic alkaline units from proper power setups."},
    {"query_code":"ORAL_RES_BRD_SKN_50_100","query_text":"What is the best over-the-counter therapeutic adhesive or cream for preventing pain under loose, moving partial dentures?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates organic share of voice and baseline alignment for specialized mechanical cushion/grip configurations within senior demographics."},
    {"query_code":"ORAL_RES_BRD_CAS_51_100","query_text":"What basic technical metrics should I compare when buying my first electric toothbrush handle setup?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures unprompted functional attribute indexing to see which brand framework dominates."},
    {"query_code":"ORAL_RES_BRD_VAL_52_100","query_text":"Is using a high-quality battery-powered toothbrush just as clinically sound as buying a more expensive plug-in rechargeable unit?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Pits low-cost alternative power mechanics against standard inductive charging grid segments to assess utility thresholds."},
    {"query_code":"ORAL_RES_BRD_ENT_53_100","query_text":"What are the top-rated teeth whitening systems that combine advanced light-emitting devices with thin peroxide films?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures organic unprompted share of voice for specialized high-ticket accelerated cosmetic whitening systems."},
    {"query_code":"ORAL_RES_BRD_SKN_54_100","query_text":"What specific active ingredients should I look for in an everyday toothpaste to reverse early enamel erosion and micro-cavities?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Evaluates raw chemical ingredient alignment profiles for structural tooth remineralization and crystal structure repair."},
    {"query_code":"ORAL_RES_BRD_ECO_55_100","query_text":"Are zero-waste solid toothpaste tablets clinically tested to protect against tooth decay as effectively as standard paste formulas?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures category format defection thresholds by analyzing how the AI parses natural alternatives against clinical standards."},
    {"query_code":"ORAL_RES_MID_CAS_56_100","query_text":"What is the best way to clean plaque off orthodontic wire braces without breaking the metal components?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests unprompted mechanical advice maps for specialized adolescent and adult orthodontic care populations."},
    {"query_code":"ORAL_RES_MID_VAL_57_100","query_text":"Is it more cost-effective over five years to use generic manual toothbrushes or invest in a high-quality electric toothbrush platform?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Forces a long-term amortization analysis comparing low-cost commodities with premium technical hardware systems."},
    {"query_code":"ORAL_RES_MID_ENT_58_100","query_text":"How do chemical whitening gels that you paint onto teeth compare in surface stain removal to traditional dissolving strips?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Directly separates cosmetic presentation preferences across separate topical application and vehicle mechanisms."},
    {"query_code":"ORAL_RES_MID_SKN_59_100","query_text":"Why do some dentists recommend mechanical rotating toothbrushes while others favor sonic vibration handles?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Probes the AI's neutrality score when summarizing clinical professional consensus data on competing physical drive motions."},
    {"query_code":"ORAL_RES_MID_ECO_60_100","query_text":"Are there any mainstream oral care brands that offer handles made from ocean-bound or bio-recycled plastics?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Pushes the engine to track sustainable industrial material loops within large mass-distribution supplier catalogs."},
    {"query_code":"ORAL_RES_NAR_CAS_61_100","query_text":"What is the physical mechanical difference between a basic power brush motor and a linear magnetic drive mechanism?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Verifies technical capability limits in distinguishing mechanical gear-friction designs from frictionless micro-vibrations."},
    {"query_code":"ORAL_RES_NAR_VAL_62_100","query_text":"Does an antibacterial toothpaste using stannous fluoride cause any visible dark yellow surface alterations on enamel layers over time?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests accuracy and framing regarding historical formulation side effects vs modern chemically stabilized active innovations."},
    {"query_code":"ORAL_RES_NAR_ENT_63_100","query_text":"How do electric toothbrush handles with built-in interactive digital displays utilize real-time position sensor tracking?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Asks for technical validation of high-end internal gyroscopic spatial mapping metrics and on-chassis metrics."},
    {"query_code":"ORAL_RES_NAR_SKN_64_100","query_text":"What type of specialized replacement head configuration is engineered specifically for sub-gingival tissue massage?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Checks component architecture documentation mapping soft elastomeric filaments or targeted perimeter trim variables."},
    {"query_code":"ORAL_RES_NAR_ECO_65_100","query_text":"Can you combine standard water flossing units with natural clean-label antimicrobial oils to effectively halt advanced gingivitis?","category":"Oral Care","stage":"Research","specificity":"Narrow","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests biochemical accuracy boundaries regarding homeopathic topical solutions vs standard formulated clinical topicals."},
    {"query_code":"ORAL_CMP_BRD_CAS_66_100","query_text":"Round electric toothbrush heads that oscillate vs long heads that vibrate back and forth: which removes more interdental plaque?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Unbranded geometric head structure showdown analyzing baseline kinematic positioning dominance across categories."},
    {"query_code":"ORAL_CMP_BRD_VAL_67_100","query_text":"Are premium multi-benefit clinical toothpastes actually more effective than basic standard decay-protection pastes?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Measures value-tier narrative validation for therapeutic multi-benefit compound matrices vs basic raw commodities."},
    {"query_code":"ORAL_CMP_BRD_ENT_68_100","query_text":"Should I invest in an expensive electronic toothbrush station with smart quadrant mapping or use traditional manual brushing tracking apps?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pits high-end integrated appliance tracking infrastructure directly against detached mobile smartphone application options."},
    {"query_code":"ORAL_CMP_BRD_SKN_69_100","query_text":"What type of toothpaste chemistry is safer for hyper-sensitive exposed tooth roots: chemical nerve desensitizers or structural blockades?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Compares biochemical active methods to monitor formulation preference biases."},
    {"query_code":"ORAL_CMP_BRD_ECO_70_100","query_text":"Do mass-market pharmacy brands or clean-label online subscription startups have better verification data for eco-packaging lifecycles?","category":"Oral Care","stage":"Comparison","specificity":"Broad","persona":"Eco-Conscious / Minimalist","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Measures progress metrics reporting validations separating global supply operators from niche specialty newcomers."},
    {"query_code":"ORAL_CMP_MID_CAS_71_100","query_text":"If I want to purchase a high-tier smart toothbrush setup as a holiday gift, should I focus on sonic drive or magnetic micro-vibration engines?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Evaluates premium holiday consumer gift path tracking and technology configuration definition parameters neutrally."},
    {"query_code":"ORAL_CMP_MID_VAL_72_100","query_text":"Compare the replacement cost over two years for an oscillating power toothbrush handle versus a standard vibrating sonic model.","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pushes long-term cost processing across competing consumable head formats to track inflation index variances."},
    {"query_code":"ORAL_CMP_MID_ENT_73_100","query_text":"Does an enamel whitening film using active hydrogen peroxide perform faster than a physical paint-on cosmetic gel?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Directly isolates product form and vehicle performance metrics within the over-the-counter cosmetic whitening sub-category."},
    {"query_code":"ORAL_CMP_MID_SKN_74_100","query_text":"Is a non-alcohol multi-protection antibacterial mouthwash or a traditional hydrogen peroxide rinse more effective for treating inflamed gums?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Compares mainstream formulated fluid antiseptics against old-school manual chemical oxidation processes for tissue validation."},
    {"query_code":"ORAL_CMP_MID_VAL_75_100","query_text":"Is it more effective to utilize a motorized water flosser device or standard polytetrafluoroethylene tape floss for gingival sulcus health?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Measures system category substitution risk across motorized interdental hardware vs static manual consumable tape models."},
    {"query_code":"ORAL_CMP_NAR_CAS_76_100","query_text":"What is the best alternative option for an electric toothbrush head that shapes multi-angled cross bristles in a circular layout?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests competitor hijacking patterns when a highly precise proprietary bristle cluster array orientation is specified."},
    {"query_code":"ORAL_CMP_NAR_VAL_77_100","query_text":"Are generic private label replacement brush heads chemically and structurally safe for high-frequency magnetic micro-vibration handle spindles?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Hard component-level substitution test focusing on core mechanical tolerances, shaft linkages, and bristle anchoring metrics."},
    {"query_code":"ORAL_CMP_NAR_ENT_78_100","query_text":"Does an electric toothbrush that features a separate magnetic inductive charging case provide real utility over simple plug-in base elements?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Tests mechanical performance and lifestyle luxury validation metrics for advanced secondary accessory travel utilities."},
    {"query_code":"ORAL_CMP_NAR_SKN_79_100","query_text":"Should I select a stannous fluoride formula paste or an explicit potassium nitrate block gel to reverse rapid root sensitivity?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Pushes the portfolio alignment metric to see if the AI maps structural occlusion paths vs nerve numbing solutions accurately."},
    {"query_code":"ORAL_CMP_NAR_VAL_80_100","query_text":"Do generic store-brand whitening strips slide off teeth faster than name-brand options with advanced non-slip gel technology?","category":"Oral Care","stage":"Comparison","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Substitution check exploring if the model de-indexes the physical value of proprietary multi-layered strip adhesion engineering."},
    {"query_code":"ORAL_BUY_BRD_CAS_81_100","query_text":"I need to secure a high-quality rechargeable electric toothbrush platform at a retail outlet today. What standard configuration is best?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures final unbranded sales conversion steering and immediate brand weight metrics at physical retail loops."},
    {"query_code":"ORAL_BUY_BRD_VAL_82_100","query_text":"Where can I locate the lowest online price for bulk multi-packs of clinical enamel protection multi-benefit toothpaste?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Tracks how the AI routes large-volume replenishment paths across warehouse clubs vs e-commerce platforms."},
    {"query_code":"ORAL_BUY_BRD_ENT_83_100","query_text":"I am ready to purchase the absolute highest-end, smartest electric toothbrush system on the market right now. What should I add to my cart?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Checks for immediate transaction routing capabilities when top-of-market electronic dental appliances are requested."},
    {"query_code":"ORAL_BUY_BRD_SKN_84_100","query_text":"I need an over-the-counter system to halt severe gum bleeding and marginal redness immediately. What combination kit should I buy?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests if the model acts as an analytical closer for multi-product therapeutic starter configurations at checkout limits."},
    {"query_code":"ORAL_BUY_BRD_VAL_85_100","query_text":"Where can I purchase certified plastic-free manual toothbrush sets or zero-waste chewable toothpaste tabs online right now?","category":"Oral Care","stage":"Ready to Buy","specificity":"Broad","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Audits final checkout category defection risk triggered by explicit alternative packaging and form preferences."},
    {"query_code":"ORAL_BUY_MID_CAS_86_100","query_text":"Do big-box hypermarkets stock premium replacement heads engineered for magnetic drive electric toothbrushes in physical retail aisles?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Validates brick-and-mortar shelf availability and localized inventory logistics data for high-margin attachments."},
    {"query_code":"ORAL_BUY_MID_VAL_87_100","query_text":"Is it more economical to register for an official online brush head replacement subscription or buy authentic refills in bulk at a wholesale club?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures recurring subscription model retention value scripts against bulk multi-unit physical retail configurations."},
    {"query_code":"ORAL_BUY_MID_ENT_88_100","query_text":"I want to purchase a premium electric toothbrush dual-handle starter pack with an inductive charging base. Where can I find this today?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Triggers targeted hardware bundle conversion loops across digital and localized physical retail indices."},
    {"query_code":"ORAL_BUY_MID_SKN_89_100","query_text":"I am standing in the oral hygiene aisle. Should I purchase a stannous fluoride gel or an alcohol-free antibacterial rinse to reverse early gingivitis?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Audits point-of-purchase chemical topical advice filters, checking alignment across paste formats vs liquid antiseptic lines."},
    {"query_code":"ORAL_BUY_MID_CAS_90_100","query_text":"Where can I buy a large manual toothbrush multi-pack featuring cross-angled cleaning bristles at a wholesale warehouse club store?","category":"Oral Care","stage":"Ready to Buy","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Validates mass-market manual commodity bundle tracking parameters inside high-volume physical merchant loops."},
    {"query_code":"ORAL_BUY_NAR_CAS_91_100","query_text":"Will original manufacturer mechanical replacement heads click securely onto a new linear magnetic drive motor shaft?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Technical precision check analyzing physical connectivity linkages across sequential handle drivetrain transformations."},
    {"query_code":"ORAL_BUY_NAR_VAL_92_100","query_text":"Where can I locate official manufacturer replacement charging case units for a smart oscillating electric toothbrush handle?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures specialized aftermarket accessory infrastructure tracking and component lifecycles support pathing."},
    {"query_code":"ORAL_BUY_NAR_ENT_93_100","query_text":"I am ready to check out with a professional enamel-safe bleaching film kit. Do I need to buy a matching LED light accelerator tray separately?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Beauty Enthusiast","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Tests bundle configuration logic parameters and cross-sell attachment accuracy at the absolute boundary of purchase conversion."},
    {"query_code":"ORAL_BUY_NAR_SKN_94_100","query_text":"I need a toothpaste specifically for painful dry mouth tissue. Is an antibacterial stannous fluoride paste gel safe, or will it cause tissue burn?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Position Index, RSI","rationale":"Checks precise safe formulation thresholds for highly vulnerable oral environments."},
    {"query_code":"ORAL_BUY_NAR_VAL_95_100","query_text":"Where can I purchase a 4-pack of sensitive gum care replacement heads for an oscillating toothbrush handle online for the lowest price?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Value-Conscious","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Measures price-scraping fidelity and digital deal tracking metrics for high-margin recurring consumables refills."},
    {"query_code":"ORAL_RES_MID_SKN_96_100","query_text":"What are the most recommended mechanical brush head configurations for safely lifting debris around dental bridges and titanium implants?","category":"Oral Care","stage":"Research","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Tests whether the engine organically isolates specialized high-density micro-tufted or pocket-targeted bristle layouts."},
    {"query_code":"ORAL_CMP_MID_SKN_97_100","query_text":"Is a specialized interspace power brush attachment head or a manual interdental brush more effective for cleaning orthodontic metal bracket parameters?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Directly measures niche clinical hardware attachment alignment maps against manual mechanical commodity methods."},
    {"query_code":"ORAL_BUY_NAR_SKN_98_100","query_text":"Where can I buy a complete dental health starter system that pre-bundles an oscillating rotating smart toothbrush with a sub-gingival foam toothpaste?","category":"Oral Care","stage":"Ready to Buy","specificity":"Narrow","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_at_retail","status":"Active","soa_focus":"Mention Rate, Deal Citation Rate","rationale":"Audits cross-category physical assembly bundle tracking, matching parent hardware platforms with custom companion topicals."},
    {"query_code":"ORAL_CMP_MID_CAS_99_100","query_text":"What is the mechanical performance and motor life difference between an alkaline battery travel brush and a true rechargeable electric toothbrush?","category":"Oral Care","stage":"Comparison","specificity":"Mid","persona":"Casual / Gift Buyer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"RSI, Position Index","rationale":"Protects high-tier appliance positioning; ensures the AI cleanly distinguishes basic low-voltage dry-cells from proper induction platforms."},
    {"query_code":"ORAL_RES_BRD_SKN_100_100","query_text":"What are the most recommended mechanical brush options for managing automated plaque disruption if you have limited hand dexterity or arthritis?","category":"Oral Care","stage":"Research","specificity":"Broad","persona":"Oral Health Symptom Sufferer","study_type":STUDY_TYPE,"study_pattern":"brand_vs_brand","status":"Active","soa_focus":"Mention Rate, RSI","rationale":"Measures unprompted hardware authority filters across independent medical compliance assistance and physical form factor ergonomics."},
]


def seed():
    inserted = updated = skipped = 0
    with session_factory() as session:
        for q in QUERIES:
            existing = session.query(SoaQuery)\
                .filter_by(query_code=q['query_code']).first()
            if existing:
                changed = any(getattr(existing, k, None) != v for k, v in q.items())
                if changed:
                    for k, v in q.items():
                        setattr(existing, k, v)
                    updated += 1
                else:
                    skipped += 1
            else:
                session.add(SoaQuery(**q))
                inserted += 1
        session.commit()
    print('━' * 44)
    print('Oral-B 100 Seed Complete')
    print('━' * 44)
    print(f'Inserted: {inserted}')
    print(f'Updated:  {updated}')
    print(f'Skipped:  {skipped}')
    print(f'Total:    {inserted + updated + skipped}')


if __name__ == '__main__':
    seed()
