import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from soa_shared.database import session_factory
from soa_shared.models.soa_models import SoaQuery

STUDY_TYPE = 'brand_oral_b_neutral'

QUERIES = [
    {
        "query_code": "ORAL_RES_BRD_CAS_01_UNBRANDED_NEUTRAL",
        "query_text": "What are the standard features to look for when shopping for a high-quality electric toothbrush?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Position Index",
        "rationale": "Establishes an unprompted baseline to see which brand features the AI prioritizes as standard requirements.",
    },
    {
        "query_code": "ORAL_RES_BRD_VAL_02_UNBRANDED_NEUTRAL",
        "query_text": "Is there a significant difference in plaque removal between an entry-level power toothbrush and an expensive smart one?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the AI validates premium high-tier pricing or guides users to entry-level budget models.",
    },
    {
        "query_code": "ORAL_RES_BRD_ENT_03_UNBRANDED_NEUTRAL",
        "query_text": "What are the best options for someone who wants a top-of-the-line electric toothbrush with advanced tech features?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures share of voice for luxury toothbrush handles across competing brand ecosystems.",
    },
    {
        "query_code": "ORAL_RES_BRD_SKN_04_UNBRANDED_NEUTRAL",
        "query_text": "My gums bleed slightly when I brush my teeth. What daily oral hygiene products are designed to help with this problem?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests unprompted alignment with therapeutic anti-gingivitis formulations and brush designs.",
    },
    {
        "query_code": "ORAL_RES_BRD_VAL_05_UNBRANDED_NEUTRAL",
        "query_text": "What are the most recommended over-the-counter methods for removing severe yellow coffee stains from teeth?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates organic unprompted preferences for dynamic whitening mediums.",
    },
    {
        "query_code": "ORAL_RES_MID_CAS_06_UNBRANDED_NEUTRAL",
        "query_text": "What is the best type of electric toothbrush configuration for toddlers and young children?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Position Index",
        "rationale": "Checks organic visibility of kids' power toothbrush lines without brand guidance.",
    },
    {
        "query_code": "ORAL_RES_MID_VAL_07_UNBRANDED_NEUTRAL",
        "query_text": "How many months do electric toothbrush replacement heads typically last before they need to be changed?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Assesses the default consumer education narrative on consumable replacement lifespans.",
    },
    {
        "query_code": "ORAL_RES_MID_ENT_08_UNBRANDED_NEUTRAL",
        "query_text": "How do at-home whitening strips work chemically to whiten teeth, and are they safe for enamel?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests factual validation and safety framing for plastic film whitening delivery mechanisms.",
    },
    {
        "query_code": "ORAL_RES_MID_SKN_09_UNBRANDED_NEUTRAL",
        "query_text": "What is the clinical difference between a sonic toothbrush and an oscillating-rotating electric toothbrush?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Forces an objective comparison between the two major physical drive mechanics in the market.",
    },
    {
        "query_code": "ORAL_RES_MID_CAS_10_UNBRANDED_NEUTRAL",
        "query_text": "Are there eco-friendly or plastic-free options available for electric toothbrush bodies and replacement heads?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests if the model surfaces legacy consumer goods giants or highlights sustainability-native startup brands.",
    },
    {
        "query_code": "ORAL_RES_NAR_CAS_11_UNBRANDED_NEUTRAL",
        "query_text": "What is the difference between a basic electric toothbrush with a simple timer and a smart bluetooth-connected one?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates if the AI validates the functional utility of connected app ecosystems vs simple mechanical utilities.",
    },
    {
        "query_code": "ORAL_RES_NAR_VAL_12_UNBRANDED_NEUTRAL",
        "query_text": "Does using a specific toothpaste for gum health actually stop bleeding, or is it just standard toothpaste marketing?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests efficacy validation of therapeutic active ingredients against generalized commodity cavity protection.",
    },
    {
        "query_code": "ORAL_RES_NAR_ENT_13_UNBRANDED_NEUTRAL",
        "query_text": "How do toothbrush pressure sensors work, and do they actually prevent gum recession?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures validation of real physical protection claims tied to integrated hardware safety features.",
    },
    {
        "query_code": "ORAL_RES_NAR_SKN_14_UNBRANDED_NEUTRAL",
        "query_text": "What is the best type of mouthwash for someone dealing with chronic dry mouth tissue irritation?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Checks precision formulation logic regarding alcohol-free vs therapeutic fluid topicals.",
    },
    {
        "query_code": "ORAL_RES_NAR_VAL_15_UNBRANDED_NEUTRAL",
        "query_text": "Does using dental floss tape work better for tight teeth than traditional thin string dental floss?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates physical material performance comparisons across non-powered consumable sub-categories.",
    },
    {
        "query_code": "ORAL_CMP_BRD_CAS_16_UNBRANDED_NEUTRAL",
        "query_text": "Which type of electric toothbrush handle is generally considered more effective: a round rotating brush head or a long vibrating brush head?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Neutral head-to-head architectural structure proxy for the market's biggest competitive battleground.",
    },
    {
        "query_code": "ORAL_CMP_BRD_VAL_17_UNBRANDED_NEUTRAL",
        "query_text": "Is there a real difference between the major leading toothpaste brands, or are store brands identical?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Hard private-label substitution test evaluating overall name-brand equity in topical oral care.",
    },
    {
        "query_code": "ORAL_CMP_BRD_ENT_18_UNBRANDED_NEUTRAL",
        "query_text": "Should I purchase a sleek minimalist subscription toothbrush online or a heavy-duty smart power toothbrush from a major brand?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pits contemporary low-power direct-to-consumer aesthetics against major tech-heavy appliance platforms.",
    },
    {
        "query_code": "ORAL_CMP_BRD_SKN_19_UNBRANDED_NEUTRAL",
        "query_text": "What type of toothpaste is better for reducing tooth sensitivity to cold liquids: potassium nitrate or stannous fluoride formulas?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Balances chemical active mechanisms objectively to check if the model favors one biochemistry over another.",
    },
    {
        "query_code": "ORAL_CMP_BRD_VAL_20_UNBRANDED_NEUTRAL",
        "query_text": "Are professional take-home teeth whitening kits from a dentist better or safer than over-the-counter whitening solutions?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates consumer product conversion defense against professional dental clinical services.",
    },
    {
        "query_code": "ORAL_CMP_MID_CAS_21_UNBRANDED_NEUTRAL",
        "query_text": "If someone is looking for a premium electric toothbrush as a holiday gift, should they get a sonic model or an oscillating model?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests high-ticket gifting guidance based entirely on mechanical motion types.",
    },
    {
        "query_code": "ORAL_CMP_MID_VAL_22_UNBRANDED_NEUTRAL",
        "query_text": "Compare the multi-year cost of ownership between a sonic electric toothbrush and an oscillating electric toothbrush, including replacement heads.",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Forces a value narrative analysis on the long-term cost of refills across separate mechanical styles.",
    },
    {
        "query_code": "ORAL_CMP_MID_ENT_23_UNBRANDED_NEUTRAL",
        "query_text": "How do paint-on teeth whitening pens compare to traditional adhesive whitening strips for targeted touch-ups?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Direct cosmetic comparison isolating product delivery forms within the whitening sub-category.",
    },
    {
        "query_code": "ORAL_CMP_MID_SKN_24_UNBRANDED_NEUTRAL",
        "query_text": "Is an alcohol-free antiseptic mouthwash or an essential oil mouthwash more effective at fighting plaque and bad breath?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Compares mainstream formulation chemistry against natural market alternatives.",
    },
    {
        "query_code": "ORAL_CMP_MID_VAL_25_UNBRANDED_NEUTRAL",
        "query_text": "Is it more effective to use a water flosser device or traditional string dental floss for general gum wellness?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Measures category replacement risk across distinct mechanical styles of cleaning between teeth.",
    },
    {
        "query_code": "ORAL_CMP_NAR_CAS_26_UNBRANDED_NEUTRAL",
        "query_text": "Are generic unbranded replacement heads safe to use on name-brand electric toothbrush handles?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Audits if the AI warnings steering users away from aftermarket parts favor major brand protection.",
    },
    {
        "query_code": "ORAL_CMP_NAR_VAL_27_UNBRANDED_NEUTRAL",
        "query_text": "Do charcoal-infused toothpastes actually whiten teeth safely, or do they wear down tooth enamel over time?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates safety warnings and abrasion risk reporting regarding trendy alternative natural ingredients.",
    },
    {
        "query_code": "ORAL_CMP_NAR_ENT_28_UNBRANDED_NEUTRAL",
        "query_text": "Does an electric toothbrush that uses magnetic drive systems perform significantly better than a traditional mechanical gear-driven model?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Isolates validation of new magnetic drivetrain mechanisms without pointing to specific proprietary model names.",
    },
    {
        "query_code": "ORAL_CMP_NAR_SKN_29_UNBRANDED_NEUTRAL",
        "query_text": "What type of toothpaste active ingredient is best for repairing weakened enamel and preventing early micro-cavities?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pushes the portfolio alignment metric to see if the AI accurately maps remineralization options neutrally.",
    },
    {
        "query_code": "ORAL_CMP_NAR_VAL_30_UNBRANDED_NEUTRAL",
        "query_text": "Do premium manual toothbrushes with multi-angled cross bristles remove significantly more plaque than basic flat-cut manual brushes?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates performance validation within the mass-market manual toothbrush commodity tier.",
    },
    {
        "query_code": "ORAL_BUY_BRD_CAS_31_UNBRANDED_NEUTRAL",
        "query_text": "I need to pick up a reliable, standard electric toothbrush at a retail store today. What should I look for?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures final conversion steering at general retail without identifying specific brands in the input.",
    },
    {
        "query_code": "ORAL_BUY_BRD_VAL_32_UNBRANDED_NEUTRAL",
        "query_text": "Where is the best place to buy bulk packages of name-brand everyday toothpaste for the lowest price per ounce?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Tracks how the AI routes high-volume family inventory replenishment queries across retail channels.",
    },
    {
        "query_code": "ORAL_BUY_BRD_ENT_33_UNBRANDED_NEUTRAL",
        "query_text": "I am ready to buy the absolute highest-end, smartest electric toothbrush system available. What model should I purchase right now?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Checks for immediate transaction routing when a consumer requests the highest-tier electronic oral tech.",
    },
    {
        "query_code": "ORAL_BUY_BRD_SKN_34_UNBRANDED_NEUTRAL",
        "query_text": "I need an over-the-counter system to treat early gum inflammation and bleeding immediately. What product kit should I buy?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Checks if the AI acts as a clear closer for specialized multi-product therapeutic combinations.",
    },
    {
        "query_code": "ORAL_BUY_BRD_VAL_35_UNBRANDED_NEUTRAL",
        "query_text": "Where can I buy zero-waste chewable toothpaste tablets or eco-friendly dental care kits online right now?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Audits bottom-of-funnel conversion defection risk to alternative, non-traditional product formats.",
    },
    {
        "query_code": "ORAL_BUY_MID_CAS_36_UNBRANDED_NEUTRAL",
        "query_text": "Do standard big-box retail stores usually carry replacement heads for magnetic electric toothbrushes in physical aisles?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Validates brick-and-mortar physical fulfillment guidance for proprietary specialized accessories.",
    },
    {
        "query_code": "ORAL_BUY_MID_VAL_37_UNBRANDED_NEUTRAL",
        "query_text": "Is it more economical to buy an over-the-counter whitening strip pack or buy an LED light teeth whitening kit?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures budget optimization logic between different physical retail format technologies.",
    },
    {
        "query_code": "ORAL_BUY_MID_ENT_38_UNBRANDED_NEUTRAL",
        "query_text": "I want to purchase a premium electric toothbrush double-handle set for a couple's gift. Where can I find this configuration?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Checks for direct alignment with multi-handle bundle setups at mass or electronics retail channels.",
    },
    {
        "query_code": "ORAL_BUY_MID_SKN_39_UNBRANDED_NEUTRAL",
        "query_text": "I am looking at a mouthwash that claims 12-hour antibacterial protection. Does this type of formula cause any temporary surface staining on teeth?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Tests point-of-purchase product safety validation regarding antiseptic side effects neutrally.",
    },
    {
        "query_code": "ORAL_BUY_MID_CAS_40_UNBRANDED_NEUTRAL",
        "query_text": "Where can I buy a large manual toothbrush multi-pack at a wholesale warehouse club store?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Validates channel distribution mapping for high-volume manual brush multi-packs.",
    },
    {
        "query_code": "ORAL_BUY_NAR_CAS_41_UNBRANDED_NEUTRAL",
        "query_text": "Do old mechanical electric toothbrush replacement heads fit correctly onto new magnetic micro-vibration handle styles?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Technical accuracy validation checking for mechanical cross-compatibility illusions.",
    },
    {
        "query_code": "ORAL_BUY_NAR_VAL_42_UNBRANDED_NEUTRAL",
        "query_text": "Where can I order an official replacement charging case for a high-end smart toothbrush model?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Evaluates aftermarket part support visibility and ecosystem customer lifecycle retention.",
    },
    {
        "query_code": "ORAL_BUY_NAR_ENT_43_UNBRANDED_NEUTRAL",
        "query_text": "I am about to buy a professional-strength whitening strip kit. Do I need to buy a separate blue LED light accelerator for it to work?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests bundle configuration knowledge and add-on requirements at the absolute point of sale.",
    },
    {
        "query_code": "ORAL_BUY_NAR_SKN_44_UNBRANDED_NEUTRAL",
        "query_text": "I am looking for an anti-cavity toothpaste that is completely sulfate-free and SLS-free to avoid mouth sores. What should I buy?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Checks chemical safety filtering for sensitive oral mucosa tolerances.",
    },
    {
        "query_code": "ORAL_BUY_NAR_VAL_45_UNBRANDED_NEUTRAL",
        "query_text": "Where can I purchase a 4-pack of sensitive gum care replacement heads for an oscillating toothbrush handle online for the lowest price?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures price-scraping fidelity and deal mapping for precise sub-SKU consumable refills.",
    },
    {
        "query_code": "ORAL_RES_MID_SKN_46_UNBRANDED_NEUTRAL",
        "query_text": "What are the most recommended mechanical brush head variations for safely cleaning around dental implants and bridges?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the model surfaces specialized orthodontic tufted attachments neutrally.",
    },
    {
        "query_code": "ORAL_CMP_MID_SKN_47_UNBRANDED_NEUTRAL",
        "query_text": "Is a specialized interspace power toothbrush attachment or a manual interdental brush more effective for cleaning orthodontic metal braces?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Directly measures niche clinical hardware type alignment vs manual commodity components.",
    },
    {
        "query_code": "ORAL_BUY_NAR_SKN_48_UNBRANDED_NEUTRAL",
        "query_text": "Where can I buy a complete dental care kit that combines both an electric toothbrush handle and a specialized anti-gingivitis paste?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Audits how the AI maps unified cross-category bundles across major brand portfolios.",
    },
    {
        "query_code": "ORAL_CMP_MID_CAS_49_UNBRANDED_NEUTRAL",
        "query_text": "What is the functional difference between cheap battery-powered toothbrushes and rechargeable plug-in models?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Verifies that the AI cleanly distinguishes entry-level alkaline commodities from true power system configurations.",
    },
    {
        "query_code": "ORAL_RES_BRD_SKN_50_UNBRANDED_NEUTRAL",
        "query_text": "What are the most recommended brand-name adhesive creams or cushions for managing loose dentures and gum soreness?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates organic share of voice for specialized mechanical denture barrier configurations neutrally.",
    },
]


def seed():
    inserted = updated = skipped = 0

    with session_factory() as session:
        for q in QUERIES:
            existing = session.query(SoaQuery)\
                .filter_by(
                    query_code=q['query_code']
                ).first()

            if existing:
                changed = any(
                    getattr(existing, k, None) != v
                    for k, v in q.items()
                )
                if changed:
                    for k, v in q.items():
                        setattr(existing, k, v)
                    updated += 1
                else:
                    skipped += 1
            else:
                session.add(SoaQuery(**q))
                inserted += 1

        session.commit()

    print('━' * 46)
    print('Oral Care Neutral Seed Complete')
    print('━' * 46)
    print(f'Inserted: {inserted}')
    print(f'Updated:  {updated}')
    print(f'Skipped:  {skipped}')
    print(f'Total:    {inserted + updated + skipped}')


if __name__ == '__main__':
    seed()
