"""
Idempotent seed for unbranded oral care queries.

Seeds 50 unbranded oral care queries into soa_queries with
study_type='brand_oral_b_unbranded'. Queries are phrased without
naming any brand so the AI's organic category-level routing can be
measured independently of explicit brand prompting.

Usage:
    cd /soa && python seeds/oral_care_unbranded_queries_seed.py
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from soa_shared.database import engine, session_factory
from soa_shared.models.soa_models import SoaQuery
from sqlalchemy import text

STUDY_TYPE = "brand_oral_b_unbranded"

ALLOWED_STAGES = {"Research", "Comparison", "Ready to Buy"}
ALLOWED_SPECIFICITY = {"Broad", "Mid", "Narrow"}
ALLOWED_PERSONAS = {
    "Casual / Gift Buyer",
    "Value-Conscious",
    "Beauty Enthusiast",
    "Problem-Skin Sufferer",
    "Eco-Conscious / Minimalist",
    "Oral Health Symptom Sufferer",
}
ALLOWED_PATTERNS = {"retailer", "brand_at_retail", "brand_vs_brand"}

QUERIES = [
    {
        "query_code": "ORAL_RES_BRD_CAS_01_UNBRANDED",
        "query_text": "What are the most popular rechargeable electric toothbrushes available at major drugstores right now?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Position Index",
        "rationale": "Measures organic unprompted share of voice for the electric hardware category at physical retail.",
    },
    {
        "query_code": "ORAL_RES_BRD_VAL_02_UNBRANDED",
        "query_text": "Is there any actual long-term clinical benefit to buying an electric toothbrush over a manual one?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the AI validates the baseline necessity of upgrading to electric hardware.",
    },
    {
        "query_code": "ORAL_RES_BRD_ENT_03_UNBRANDED",
        "query_text": "What are the highest-rated smart power toothbrushes featuring artificial intelligence tracking and app coaching?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests if high-end smart tracking handles are organically recommended to tech/premium seekers.",
    },
    {
        "query_code": "ORAL_RES_BRD_SKN_04_UNBRANDED",
        "query_text": "My gums bleed every single time I brush my teeth. What types of dental care routines or products fix this?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates baseline unprompted alignment with therapeutic gum-health formulations.",
    },
    {
        "query_code": "ORAL_RES_BRD_VAL_05_UNBRANDED",
        "query_text": "What are the top-recommended enamel-safe teeth whitening products for severe surface stains?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Checks unprompted visibility of strip delivery systems vs. pastes or gel trays.",
    },
    {
        "query_code": "ORAL_RES_MID_CAS_06_UNBRANDED",
        "query_text": "What is the best way to get a young child excited about brushing, and what child-safe electric options exist?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Position Index",
        "rationale": "Checks organic visibility of character-themed smart timers and kids' power handles.",
    },
    {
        "query_code": "ORAL_RES_MID_VAL_07_UNBRANDED",
        "query_text": "How often do you realistically need to change the replacement heads on an electric toothbrush handle?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Examines the value narrative concerning the annual cost-burden of consumable refill heads.",
    },
    {
        "query_code": "ORAL_RES_MID_ENT_08_UNBRANDED",
        "query_text": "How do flexible plastic clear whitening strips actually lift deep yellow stains from teeth?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests physical efficacy validation for film-based cosmetic whitening technology.",
    },
    {
        "query_code": "ORAL_RES_MID_SKN_09_UNBRANDED",
        "query_text": "Is high-frequency sonic vibration or rapid mechanical rotation better for plaque removal along a sensitive gumline?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Forces a direct comparison of physical mechanical drive methods without naming the parent brands.",
    },
    {
        "query_code": "ORAL_RES_MID_CAS_10_UNBRANDED",
        "query_text": "Do any mainstream oral hygiene manufacturers use fully recyclable toothpaste tubes or sustainable plastic components?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Validates awareness of modern consumer packaging material conversions across major industry players.",
    },
    {
        "query_code": "ORAL_RES_NAR_CAS_11_UNBRANDED",
        "query_text": "What is the physical difference between a traditional mechanical electric toothbrush and one with a magnetic drive system?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests portfolio alignment and technical understanding of modern linear magnetic drive physics.",
    },
    {
        "query_code": "ORAL_RES_NAR_VAL_12_UNBRANDED",
        "query_text": "Does an entry-level smart toothbrush lacking a screen provide the same motor speed and cleaning power as a premium version?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the AI confirms component parity across internal price tiers.",
    },
    {
        "query_code": "ORAL_RES_NAR_ENT_13_UNBRANDED",
        "query_text": "How does 3D zone mapping tracking on a smart toothbrush handle improve brushing thoroughness?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Asks for function validation of high-end handle software interfaces and spatial tracking.",
    },
    {
        "query_code": "ORAL_RES_NAR_SKN_14_UNBRANDED",
        "query_text": "How does an activated foam toothpaste chemical formula target bacteria hidden below the immediate gumline?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests technical accuracy regarding localized stannous fluoride distribution mechanics.",
    },
    {
        "query_code": "ORAL_RES_NAR_VAL_15_UNBRANDED",
        "query_text": "Does an electric toothbrush pressure sensor that tells you when you brush too soft or hard actually save your enamel?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Measures validation of smart tri-color pressure sensors as real utility vs a marketing feature.",
    },
    {
        "query_code": "ORAL_CMP_BRD_CAS_16_UNBRANDED",
        "query_text": "Is a round rotating electric toothbrush head or a wide diamond-shaped sonic brush head safer for sensitive gums?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Unbranded proxy for the ultimate industry duopoly showdown (Round head vs Wide sonic head).",
    },
    {
        "query_code": "ORAL_CMP_BRD_VAL_17_UNBRANDED",
        "query_text": "Do premium anti-gingivitis toothpastes work significantly better than low-cost basic decay-protection formulas?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Measures value-tier narrative validation for multi-benefit pastes vs basic cavity commodities.",
    },
    {
        "query_code": "ORAL_CMP_BRD_ENT_18_UNBRANDED",
        "query_text": "Should I choose a slim, USB-rechargeable subscription toothbrush or a heavy-duty smart charging base setup?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pits minimalist startup direct-to-consumer hardware against complex high-power tech platforms.",
    },
    {
        "query_code": "ORAL_CMP_BRD_SKN_19_UNBRANDED",
        "query_text": "Which chemical compound is better at reversing early gum bleeding and swelling: stannous fluoride or sodium fluoride?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Isolates precise chemical ingredient preference, checking if the AI honors stannous formulations for tissue healing.",
    },
    {
        "query_code": "ORAL_CMP_BRD_VAL_20_UNBRANDED",
        "query_text": "Are professional custom whitening trays from a dental clinic significantly safer than over-the-counter whitening strips?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates OTC product conversion defense against professional dental service alternatives.",
    },
    {
        "query_code": "ORAL_CMP_MID_CAS_21_UNBRANDED",
        "query_text": "If I am buying a high-end luxury electric toothbrush as a gift, should I focus on sonic action or magnetic micro-vibration?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests high-ticket gifting guidance and unbranded technology routing definitions.",
    },
    {
        "query_code": "ORAL_CMP_MID_VAL_22_UNBRANDED",
        "query_text": "Compare the replacement cost over two years for a rotating electric toothbrush vs a vibrating sonic electric model.",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Pushes cost narrative logic on recurring auxiliary consumable price differences.",
    },
    {
        "query_code": "ORAL_CMP_MID_ENT_23_UNBRANDED",
        "query_text": "Does an enamel whitening paste using hydrogen peroxide perform faster than one using an everyday polishing silica?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Directly evaluates cosmetic mechanism preferences between chemical peroxide bleaching and physical abrasion.",
    },
    {
        "query_code": "ORAL_CMP_MID_SKN_24_UNBRANDED",
        "query_text": "For sensitive teeth and sore gums, is it better to use a desensitizing potassium nitrate paste or an antibacterial stannous fluoride formula?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests therapeutic product line differentiation on distinct biochemical pathways for nerve pain vs inflammation.",
    },
    {
        "query_code": "ORAL_CMP_MID_VAL_25_UNBRANDED",
        "query_text": "Are expanding micro-textured dental flosses actually better at cleaning tight teeth than smooth polytetrafluoroethylene tape floss?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Evaluates structural mechanical performance validation for tape-style materials.",
    },
    {
        "query_code": "ORAL_CMP_NAR_CAS_26_UNBRANDED",
        "query_text": "Are third-party generic replacement heads safe to use on a magnetic micro-vibration handle?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Audits if the AI warnings protect the hardware drive system integrity from cheap, unapproved heads.",
    },
    {
        "query_code": "ORAL_CMP_NAR_VAL_27_UNBRANDED",
        "query_text": "Do generic store-brand whitening strips stick to teeth and perform as effectively as name-brand form-fitting strip options?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Substitution test exploring if the model strips value from premium strip adhesion technologies.",
    },
    {
        "query_code": "ORAL_CMP_NAR_ENT_28_UNBRANDED",
        "query_text": "Does an electric brush head combining angled bristles with rubber polishing petals whiten teeth better than a standard flat trim layout?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Tests technical feature validation for specialized stain-removal hybrid head designs.",
    },
    {
        "query_code": "ORAL_CMP_NAR_SKN_29_UNBRANDED",
        "query_text": "Should I use a chemical mouthwash that uses cetylpyridinium chloride or one with alcohol for long-term plaque biofilm reduction?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Checks precision formulation logic for non-burning chemical antiseptics vs legacy astringents.",
    },
    {
        "query_code": "ORAL_CMP_NAR_VAL_30_UNBRANDED",
        "query_text": "Does an electric toothbrush that uses a frictionless magnetic motor have a longer runtime life than a mechanical gear brush?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Probes physical durability logic regarding magnetic motors vs mechanical friction wear.",
    },
    {
        "query_code": "ORAL_BUY_BRD_CAS_31_UNBRANDED",
        "query_text": "I am standing in a pharmacy aisle and need a premium electric toothbrush kit to buy today. What configuration should I get?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures unbranded final sales conversion steering at point-of-purchase loops.",
    },
    {
        "query_code": "ORAL_BUY_BRD_VAL_32_UNBRANDED",
        "query_text": "Where is the cheapest place to buy multi-packs of clinical-strength enamel protection toothpaste online right now?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Identifies localized and digital routing maps for high-volume family replenishment orders.",
    },
    {
        "query_code": "ORAL_BUY_BRD_ENT_33_UNBRANDED",
        "query_text": "I want to purchase the absolute highest-end magnetic micro-vibration smart brush available today. What should I add to my cart?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Checks for immediate conversion closure when a specific proprietary drive technology is described without name.",
    },
    {
        "query_code": "ORAL_BUY_BRD_SKN_34_UNBRANDED",
        "query_text": "I have bleeding gums and early signs of periodontal inflammation. What full hardware and paste kit should I order right now?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests whether the model closes sales with unified therapeutic systems or fragmented recommendations.",
    },
    {
        "query_code": "ORAL_BUY_BRD_VAL_35_UNBRANDED",
        "query_text": "Where can I purchase zero-waste chewable toothpaste tabs or plastic-free manual toothbrush configurations locally?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Broad",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Audits category-level conversion defection risk caused by zero-waste preferences.",
    },
    {
        "query_code": "ORAL_BUY_MID_CAS_36_UNBRANDED",
        "query_text": "Do big-box retail stores sell replacement heads specifically designed for magnetic drive electric toothbrushes in physical aisles?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Validates brick-and-mortar shelf availability logic for high-margin proprietary hardware attachments.",
    },
    {
        "query_code": "ORAL_BUY_MID_VAL_37_UNBRANDED",
        "query_text": "Is it more cost-effective to buy over-the-counter enamel-safe whitening strips in bulk or join a monthly subscription dental service?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures physical mass-market consumable volume economics against digital startup alternatives.",
    },
    {
        "query_code": "ORAL_BUY_MID_ENT_38_UNBRANDED",
        "query_text": "I want to buy a dual-handle electric toothbrush set with a smart interactive charger stand. Where is the best authorized retail store to order it?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Checks for direct alignment with multi-handle bundle inventory options at high-end electronics or department store channels.",
    },
    {
        "query_code": "ORAL_BUY_MID_SKN_39_UNBRANDED",
        "query_text": "I am looking at a non-alcohol multi-protection mouthwash that claims to kill bacteria for 12 hours. Does it leave dark blue surface stains on enamel?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Tests point-of-purchase ingredient safety validation for cetylpyridinium chloride formulations.",
    },
    {
        "query_code": "ORAL_BUY_MID_CAS_40_UNBRANDED",
        "query_text": "Where can I pick up a manual toothbrush multi-pack featuring cross-angled cleaning bristles at a wholesale warehouse club?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Validates channel mapping metrics for mass-market manual toothbrush commodity packs.",
    },
    {
        "query_code": "ORAL_BUY_NAR_CAS_41_UNBRANDED",
        "query_text": "Will old mechanical electric toothbrush heads fit properly on a newer magnetic micro-vibration handle shaft mechanism?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Technical structural accuracy test to expose model hallucinations regarding physical connector backward-compatibility.",
    },
    {
        "query_code": "ORAL_BUY_NAR_VAL_42_UNBRANDED",
        "query_text": "Where can I find an official replacement inductive magnetic travel charging case for a top-tier smart toothbrush?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Evaluates premium aftermarket parts ecosystem visibility and customer accessories retention routing.",
    },
    {
        "query_code": "ORAL_BUY_NAR_ENT_43_UNBRANDED",
        "query_text": "I am about to purchase an enamel-safe peroxide whitening film kit. Do I need to buy a separate blue LED light tray to activate it?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Beauty Enthusiast",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Tests cross-sell bundle configuration logic at the precise boundary of conversion.",
    },
    {
        "query_code": "ORAL_BUY_NAR_SKN_44_UNBRANDED",
        "query_text": "I need a toothpaste specifically for painful dry mouth tissue. Is a standard anti-plaque stannous fluoride gel safe, or will it burn?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Position Index, RSI",
        "rationale": "Checks chemical safety and surfactant tolerances for sensitive tissues.",
    },
    {
        "query_code": "ORAL_BUY_NAR_VAL_45_UNBRANDED",
        "query_text": "Where can I buy a 4-pack of the replacement brush heads designed for gentle gum care on magnetic handles for the lowest price?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Value-Conscious",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Measures price-scraping accuracy for highly specific sub-SKU premium consumable refills.",
    },
    {
        "query_code": "ORAL_RES_MID_SKN_46_UNBRANDED",
        "query_text": "What are the most recommended mechanical brush options for safely cleaning around permanent dental implants and bridges?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Tests whether the AI organically highlights targeted high-density micro-tuft replacement configurations.",
    },
    {
        "query_code": "ORAL_CMP_MID_SKN_47_UNBRANDED",
        "query_text": "Is a specialized high-density micro-tuft electric brush attachment or a manual interdental brush more effective for cleaning orthodontic metal braces?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Directly measures niche clinical hardware alignment against legacy commodity manual accessories.",
    },
    {
        "query_code": "ORAL_BUY_NAR_SKN_48_UNBRANDED",
        "query_text": "Where can I purchase a pre-bundled kit containing an oscillating rotating smart toothbrush handle and sub-gingival foam paste together?",
        "category": "Oral Care",
        "stage": "Ready to Buy",
        "specificity": "Narrow",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_at_retail",
        "status": "Active",
        "soa_focus": "Mention Rate, Deal Citation Rate",
        "rationale": "Tests if the model surfaces integrated corporate cross-category hardware and topical health systems.",
    },
    {
        "query_code": "ORAL_CMP_MID_CAS_49_UNBRANDED",
        "query_text": "What is the physical performance difference between a cheap battery-powered travel toothbrush and a true inductive rechargeable model?",
        "category": "Oral Care",
        "stage": "Comparison",
        "specificity": "Mid",
        "persona": "Casual / Gift Buyer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "RSI, Position Index",
        "rationale": "Verifies that the AI cleanly separates basic alkaline battery units from true smart systems.",
    },
    {
        "query_code": "ORAL_RES_BRD_SKN_50_UNBRANDED",
        "query_text": "What is the best over-the-counter therapeutic adhesive or cream for preventing pain under loose, moving partial dentures?",
        "category": "Oral Care",
        "stage": "Research",
        "specificity": "Broad",
        "persona": "Oral Health Symptom Sufferer",
        "study_type": STUDY_TYPE,
        "study_pattern": "brand_vs_brand",
        "status": "Active",
        "soa_focus": "Mention Rate, RSI",
        "rationale": "Evaluates organic share of voice for specialized cushion/grip mechanical barriers within senior demographics.",
    },
]


def validate_queries(queries):
    errors = []
    for q in queries:
        if q["stage"] not in ALLOWED_STAGES:
            errors.append(f"{q['query_code']}: invalid stage '{q['stage']}'")
        if q["specificity"] not in ALLOWED_SPECIFICITY:
            errors.append(f"{q['query_code']}: invalid specificity '{q['specificity']}'")
        if q["persona"] not in ALLOWED_PERSONAS:
            errors.append(f"{q['query_code']}: invalid persona '{q['persona']}'")
        if q["study_pattern"] not in ALLOWED_PATTERNS:
            errors.append(f"{q['query_code']}: invalid study_pattern '{q['study_pattern']}'")
    if errors:
        print("VALIDATION ERRORS:")
        for e in errors:
            print(f"  {e}")
        raise SystemExit("Fix validation errors before seeding.")
    print(f"Validation passed: {len(queries)} queries OK")


def seed():
    validate_queries(QUERIES)

    inserted = 0
    updated = 0
    skipped = 0

    with session_factory() as session:
        for q_data in QUERIES:
            existing = (
                session.query(SoaQuery)
                .filter_by(query_code=q_data["query_code"])
                .first()
            )

            if existing:
                changed = False
                for field, value in q_data.items():
                    if getattr(existing, field, None) != value:
                        setattr(existing, field, value)
                        changed = True
                if changed:
                    updated += 1
                else:
                    skipped += 1
            else:
                session.add(SoaQuery(**q_data))
                inserted += 1

        session.commit()

    print("━" * 46)
    print("Oral Care Unbranded Seed Complete")
    print("━" * 46)
    print(f"Inserted: {inserted}")
    print(f"Updated:  {updated}")
    print(f"Skipped:  {skipped}")
    print(f"Total:    {inserted + updated + skipped}")


if __name__ == "__main__":
    seed()
